# -*- coding: utf-8 -*-
"""CHANA Pseudo Labelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYBHbLhravkytz3jAknby09Gh5C68-iB
"""

# CELL 1: SETUP, INFERENCE, AND CONFIDENCE ANALYSIS
# ---------------------------------------------------------
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, models, Model, Input
import tensorflow.keras.applications as applications
import gc

# Mount Drive
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- CONFIGURATION ---
# Path to your unlabeled images
UNLABELED_DIR = '/content/drive/MyDrive/CHANA_files/unlabelled_preprocessed'
WEIGHTS_PATH = '/content/drive/MyDrive/CHANA_files/transunet_stage3_real_finetune.weights.h5'

# --- ARCHITECTURE DEFINITION (Must Match Training) ---
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)
GROUPS = 8

class AddPositionEmbedding(layers.Layer):
    def __init__(self, transformer_dim, max_len=65536, **kwargs):
        super().__init__(**kwargs)
        self.transformer_dim = transformer_dim
        self.pos_embedding = layers.Embedding(input_dim=max_len, output_dim=transformer_dim)
    def call(self, x):
        seq_len = tf.shape(x)[1]
        positions = tf.range(start=0, limit=seq_len, delta=1)
        return x + self.pos_embedding(positions)

def build_transformer_bottleneck(input_tensor, transformer_dim=384, num_heads=6, num_layers=2, output_filters=512):
    x = layers.Conv2D(transformer_dim, (1, 1), padding='same', kernel_initializer='he_normal')(input_tensor)
    x = layers.GroupNormalization(groups=GROUPS)(x)
    patch_seq = layers.Reshape((input_tensor.shape[1] * input_tensor.shape[2], transformer_dim))(x)
    x = AddPositionEmbedding(transformer_dim)(patch_seq)
    for _ in range(num_layers):
        attn_output = layers.MultiHeadAttention(num_heads=num_heads, key_dim=transformer_dim // num_heads, dropout=0.1)(x, x)
        x = layers.Add()([x, attn_output])
        x = layers.LayerNormalization(epsilon=1e-6)(x)
        ffn_output = layers.Dense(transformer_dim * 4, activation='relu')(x)
        ffn_output = layers.Dense(transformer_dim)(ffn_output)
        x = layers.Add()([x, ffn_output])
        x = layers.LayerNormalization(epsilon=1e-6)(x)
    bottleneck_features = layers.Reshape((input_tensor.shape[1], input_tensor.shape[2], transformer_dim))(x)
    output = layers.Conv2D(output_filters, (1, 1), padding='same', activation='relu', kernel_initializer='he_normal')(bottleneck_features)
    output = layers.GroupNormalization(groups=GROUPS)(output)
    return output

def decoder_block(input_tensor, concat_tensor, num_filters):
    x = layers.Conv2DTranspose(num_filters, (2, 2), strides=(2, 2), padding='same')(input_tensor)
    def robust_resize(args):
        img, target = args
        return tf.image.resize(img, tf.shape(target)[1:3])
    x = layers.Lambda(robust_resize)([x, concat_tensor])
    x = layers.concatenate([x, concat_tensor], axis=-1)
    x = layers.Conv2D(num_filters, (3, 3), padding='same', kernel_initializer='he_normal')(x)
    x = layers.GroupNormalization(groups=GROUPS)(x); x = layers.Activation('relu')(x)
    x = layers.Conv2D(num_filters, (3, 3), padding='same', kernel_initializer='he_normal')(x)
    x = layers.GroupNormalization(groups=GROUPS)(x); x = layers.Activation('relu')(x)
    return x

def build_custom_unet(input_shape, num_classes):
    inputs = Input(shape=input_shape)
    backbone = applications.EfficientNetB0(weights='imagenet', include_top=False, input_tensor=inputs)
    backbone.trainable = False
    for layer in backbone.layers:
        if isinstance(layer, layers.BatchNormalization): layer.trainable = True
    s1 = backbone.get_layer('block2a_expand_activation').output
    s2 = backbone.get_layer('block3a_expand_activation').output
    s3 = backbone.get_layer('block4a_expand_activation').output
    s4 = backbone.get_layer('block6a_expand_activation').output
    bridge = backbone.get_layer('top_activation').output
    trans_bottleneck = build_transformer_bottleneck(bridge)
    d1 = decoder_block(trans_bottleneck, s4, 512)
    d2 = decoder_block(d1, s3, 256)
    ds1 = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', name='aux1', dtype='float32')(d2)
    d3 = decoder_block(d2, s2, 128)
    ds2 = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', name='aux2', dtype='float32')(d3)
    d4 = decoder_block(d3, s1, 64)
    d5 = layers.Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(d4)
    d5 = layers.Conv2D(32, (3, 3), padding='same', activation='relu')(d5)
    outputs = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', dtype='float32', name='final')(d5)
    return Model(inputs=inputs, outputs=[outputs, ds1, ds2])

# --- LOAD MODEL ---
print("🏗️ Building Model...")
model = build_custom_unet((512, 512, 3), 1)
if os.path.exists(WEIGHTS_PATH):
    model.load_weights(WEIGHTS_PATH)
    print("✅ Weights Loaded.")
else:
    raise FileNotFoundError("Weights file not found!")

# --- INFERENCE LOOP ---
print(f"🚀 Analyzing Unlabeled Data in {UNLABELED_DIR}...")
files = [f for f in os.listdir(UNLABELED_DIR) if f.lower().endswith(('.png', '.jpg', '.tif'))]

# We will store results in RAM to avoid re-running inference in Cell 2
# Structure: {'filename': str, 'confidence': float, 'pred_mask': np.array (uint8 compressed), 'img_raw': np.array}
cached_predictions = []
confidence_scores = []

for i, f in enumerate(files):
    try:
        # Preprocess
        img_path = os.path.join(UNLABELED_DIR, f)
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_raw = cv2.resize(img, (512, 512), interpolation=cv2.INTER_AREA) # Keep for saving

        # Normalize for Model
        norm_img = img_raw.astype(np.float32) / 255.0
        norm_img = (norm_img - IMAGENET_MEAN) / IMAGENET_STD

        # Predict
        pred_prob = model.predict(np.expand_dims(norm_img, 0), verbose=0)[0][0] # (512, 512, 1)

        # --- CALCULATE CONFIDENCE ---
        # Metric: Mean probability of pixels that the model "thinks" are cells (>0.5)
        # If the model finds nothing, confidence is 0.
        cell_pixels = pred_prob[pred_prob > 0.5]

        if cell_pixels.size > 0:
            conf = np.mean(cell_pixels)
        else:
            conf = 0.0

        confidence_scores.append(conf)

        # Cache (Compress mask to uint8 to save RAM: 0-255)
        # We only cache if conf > 0.5 to save memory (totally empty images are useless anyway)
        if conf > 0.5:
            cached_predictions.append({
                'filename': f,
                'confidence': conf,
                'pred_prob': (pred_prob * 255).astype(np.uint8), # Store as uint8 0-255
                'img_raw': img_raw
            })

    except Exception as e:
        print(f"Error on {f}: {e}")

    if i % 100 == 0: print(f"   Processed {i}/{len(files)}...")

# --- PLOT DISTRIBUTION ---
print("\n📊 PLOTTING CONFIDENCE DISTRIBUTION...")
plt.figure(figsize=(10, 6))
sns.histplot(confidence_scores, bins=30, kde=True, color='purple')
plt.title("Model Confidence on Unlabeled Data")
plt.xlabel("Mean Confidence of Predicted Objects (0.0 - 1.0)")
plt.ylabel("Count of Images")
plt.axvline(0.90, color='red', linestyle='--', label='Threshold 0.90')
plt.axvline(0.95, color='orange', linestyle='--', label='Threshold 0.95')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print(f"Total Images: {len(files)}")
print(f"Potential candidates > 0.90: {sum(c > 0.90 for c in confidence_scores)}")
print(f"Potential candidates > 0.95: {sum(c > 0.95 for c in confidence_scores)}")

# CELL 1.5: CIRCULARITY DISTRIBUTION ANALYSIS (FIXED)
# ---------------------------------------------------------
import math
import pandas as pd
from skimage import measure
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

if 'cached_predictions' not in locals():
    raise ValueError("❌ Please run Cell 1 first to generate 'cached_predictions'!")

print(f"📐 Analyzing Geometry of {len(cached_predictions)} candidate images...")

all_circularities = []
# We track how many images survive at different strictness levels
images_kept_at_threshold = {0.4: 0, 0.5: 0, 0.6: 0, 0.7: 0, 0.8: 0}
total_objects = 0

for item in cached_predictions:
    # Get Binary Mask
    prob_map = item['pred_prob'].astype(np.float32) / 255.0

    # --- FIX: SQUEEZE TO ENSURE 2D (512, 512) ---
    # The error happened because it was (512, 512, 1)
    mask = np.squeeze((prob_map > 0.5).astype(np.uint8))

    labeled = measure.label(mask)
    regions = measure.regionprops(labeled)

    # Check this image against multiple thresholds
    max_circ_in_image = 0

    for r in regions:
        if r.area < 100: continue # Ignore specks
        if r.perimeter == 0: continue

        circ = (4 * math.pi * r.area) / (r.perimeter ** 2)
        all_circularities.append(circ)
        total_objects += 1

        if circ > max_circ_in_image:
            max_circ_in_image = circ

    # Track "Image Survival Rate"
    for t in images_kept_at_threshold.keys():
        if max_circ_in_image >= t:
            images_kept_at_threshold[t] += 1

# --- PLOTTING ---
plt.figure(figsize=(14, 6))

# Plot 1: Object Circularity Distribution
plt.subplot(1, 2, 1)
sns.histplot(all_circularities, bins=40, kde=True, color='teal')
plt.title("Object Circularity Distribution")
plt.xlabel("Circularity (1.0 = Perfect Circle, <0.4 = Debris)")
plt.ylabel("Count of Objects")
plt.axvline(0.5, color='red', linestyle='--', label='Threshold 0.5')
plt.axvline(0.6, color='orange', linestyle='--', label='Threshold 0.6')
plt.legend()

# Plot 2: Dataset Yield Curve
plt.subplot(1, 2, 2)
thresholds = list(images_kept_at_threshold.keys())
yields = [count / len(cached_predictions) * 100 for count in images_kept_at_threshold.values()]

sns.lineplot(x=thresholds, y=yields, marker='o', color='crimson', linewidth=2)
plt.title("Dataset Yield vs. Shape Threshold")
plt.xlabel("Minimum Circularity Required")
plt.ylabel("% of Images Kept")
plt.grid(True, alpha=0.3)
plt.ylim(0, 105)

plt.tight_layout()
plt.show()

# --- STATS TABLE ---
print("\n📊 IMPACT ANALYSIS:")
print(f"Total Objects Detected: {total_objects}")
print("-" * 65)
print(f"{'Threshold':<15} | {'Objects Kept (%)':<20} | {'Images Kept (%)':<20}")
print("-" * 65)

for t in thresholds:
    obj_kept = sum(c >= t for c in all_circularities)
    obj_pct = (obj_kept / total_objects) * 100 if total_objects > 0 else 0
    img_pct = (images_kept_at_threshold[t] / len(cached_predictions)) * 100

    print(f"{t:<15.1f} | {obj_pct:<20.1f}% | {img_pct:<20.1f}%")
print("-" * 65)

# CELL 2: GENERATE SMART PSEUDO-LABELS (FIXED 3D ERROR)
# ---------------------------------------------------------
import shutil
import math
from skimage import measure

# --- CONFIGURATION (UPDATE THESE BASED ON CELL 1.5 OUTPUT) ---
FINAL_THRESHOLD = 0.95
MIN_CIRCULARITY = 0.60  # <--- Set this based on the plot you just generated
OUTPUT_DIR = '/content/drive/MyDrive/CHANA_files/pseudo_train_data'

# Setup Folders
img_out = os.path.join(OUTPUT_DIR, 'images')
mask_out = os.path.join(OUTPUT_DIR, 'masks')
os.makedirs(img_out, exist_ok=True)
os.makedirs(mask_out, exist_ok=True)

# --- HELPER: SHAPE GUARD (FIXED) ---
def filter_mask_by_shape(binary_mask, min_circ=0.5):
    """Removes jagged/irregular objects from the binary mask."""
    # SQUEEZE IS CRITICAL HERE
    binary_mask = np.squeeze(binary_mask)

    labeled = measure.label(binary_mask)
    cleaned = np.zeros_like(binary_mask)

    for region in measure.regionprops(labeled):
        if region.area < 100: continue
        if region.perimeter == 0: continue

        circularity = (4 * math.pi * region.area) / (region.perimeter ** 2)

        if circularity >= min_circ:
            coords = region.coords
            cleaned[coords[:, 0], coords[:, 1]] = 255

    return cleaned

# --- EXECUTION ---
print(f"🚀 Generating Pseudo-Labels (Conf > {FINAL_THRESHOLD} & Circ > {MIN_CIRCULARITY})...")
saved_count = 0

for item in cached_predictions:
    if item['confidence'] >= FINAL_THRESHOLD:

        # Prepare Raw Mask
        prob_map = item['pred_prob'].astype(np.float32) / 255.0
        # Create binary (0 or 1) and ensure 2D
        raw_mask = np.squeeze((prob_map > 0.5).astype(np.uint8))

        # Filter
        final_mask = filter_mask_by_shape(raw_mask, min_circ=MIN_CIRCULARITY)

        # Only save if content exists
        if np.sum(final_mask) > 0:
            fname = os.path.splitext(item['filename'])[0]

            # Save Image (RGB -> BGR)
            cv2.imwrite(os.path.join(img_out, f"{fname}.png"),
                        cv2.cvtColor(item['img_raw'], cv2.COLOR_RGB2BGR))

            # Save Mask
            cv2.imwrite(os.path.join(mask_out, f"{fname}_mask.png"), final_mask)

            saved_count += 1

print(f"\n✅ SUCCESS!")
print(f"   Saved {saved_count} clean training pairs.")
print(f"   Location: {OUTPUT_DIR}")

# CELL 3: VISUAL VERIFICATION GRID (STANDALONE)
# ---------------------------------------------------------
import os
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import measure
from google.colab import drive

# 1. MOUNT DRIVE (Required if runtime was restarted)
if not os.path.exists('/content/drive'):
    print("Mounted Drive...")
    drive.mount('/content/drive')

# --- CONFIG ---
PSEUDO_DIR = '/content/drive/MyDrive/CHANA_files/pseudo_train_data'
IMG_DIR = os.path.join(PSEUDO_DIR, 'images')
MASK_DIR = os.path.join(PSEUDO_DIR, 'masks')

# --- VERIFICATION LOOP ---
if not os.path.exists(IMG_DIR):
    print(f"❌ Error: Directory not found: {IMG_DIR}")
    print("   Did you run the Generator Cell (Cell 2) completely?")
else:
    # Get all image files
    all_files = [f for f in os.listdir(IMG_DIR) if f.endswith(('.png', '.jpg'))]

    if len(all_files) == 0:
        print("⚠️ Directory exists but is empty. Check your threshold settings.")
    else:
        # Sample 15 images (or fewer if folder is small)
        sample_size = min(15, len(all_files))
        selected_files = random.sample(all_files, sample_size)

        print(f"📸 Visualizing {sample_size} random pseudo-labels from {len(all_files)} total...")

        # --- PLOTTING ---
        plt.figure(figsize=(20, 12))

        for i, fname in enumerate(selected_files):
            # Paths
            img_path = os.path.join(IMG_DIR, fname)
            # Handle potential naming difference
            mask_name = fname.replace('.png', '_mask.png').replace('.jpg', '_mask.png')
            mask_path = os.path.join(MASK_DIR, mask_name)

            # Load Image
            img = cv2.imread(img_path)
            if img is None: continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            # Load Mask
            if os.path.exists(mask_path):
                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

                # Binarize
                _, mask = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)

                # Count Objects
                labeled_mask = measure.label(mask)
                obj_count = labeled_mask.max()

                # Create Visualization
                # 1. Red fill overlay
                overlay = img.copy()
                overlay[mask == 255] = [255, 0, 0] # Red

                # 2. Blend
                alpha = 0.4
                img_viz = cv2.addWeighted(overlay, alpha, img, 1 - alpha, 0)

                # 3. Yellow Contours (for sharp edges)
                contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                cv2.drawContours(img_viz, contours, -1, (255, 255, 0), 2)

                title_text = f"Count: {obj_count}"
            else:
                img_viz = img
                title_text = "MASK MISSING"

            # Plot
            plt.subplot(3, 5, i+1)
            plt.imshow(img_viz)
            plt.title(f"{fname[:10]}...\n{title_text}", fontsize=10)
            plt.axis('off')

        plt.tight_layout()
        plt.show()

# CELL 4: FOLDER DIAGNOSTICS & CLEANUP
# ---------------------------------------------------------
import os

# --- CONFIG ---
PSEUDO_DIR = '/content/drive/MyDrive/CHANA_files/pseudo_train_data'
IMG_DIR = os.path.join(PSEUDO_DIR, 'images')
MASK_DIR = os.path.join(PSEUDO_DIR, 'masks')

# --- CHECK ---
if not os.path.exists(IMG_DIR):
    print("❌ Critical Error: Folder does not exist.")
else:
    images = sorted([f for f in os.listdir(IMG_DIR) if f.endswith(('.png', '.jpg'))])
    masks = sorted([f for f in os.listdir(MASK_DIR) if f.endswith('.png')])

    print(f"📂 Folder Status:")
    print(f"   - Images found: {len(images)}")
    print(f"   - Masks found:  {len(masks)}")

    # Check for Pairs
    valid_pairs = 0
    orphans = []

    for img_name in images:
        # Construct expected mask name
        mask_name = img_name.replace('.png', '_mask.png').replace('.jpg', '_mask.png')
        if mask_name in masks:
            valid_pairs += 1
        else:
            orphans.append(img_name)

    print(f"\n✅ VALID PAIRS (Ready for Training): {valid_pairs}")

    if len(orphans) > 0:
        print(f"⚠️ FOUND {len(orphans)} ORPHAN IMAGES (Missing Masks).")
        print("   This confirms Google Drive was interrupted while writing.")
    elif valid_pairs < 2050:
         print("\nℹ️ NOTE: The count is lower than 2050.")
         print("   This likely means Google Drive 'gave up' syncing when the runtime restarted.")
         print("   However, 847 is WITHIN TARGET (800-1000) for Phase 4.")