# -*- coding: utf-8 -*-
"""CHANA DiffusionV2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174X-RwJsMld_Ox7KR3MbSzmYx4H0j9Js
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, utils
import numpy as np
import cv2
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

# 1. Mount Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Path Configuration (Verified against your directory structure)
DRIVE_BASE = '/content/drive/MyDrive/CHANA_files'
REAL_DATA_DIR = os.path.join(DRIVE_BASE, 'preprocessed_rgb') # Real Images Only
SYNTH_INPUT_DIR = os.path.join(DRIVE_BASE, 'synthetic_training_data_v1_ancestral') # Synth Pairs
REFINED_OUT_DIR = os.path.join(DRIVE_BASE, 'synthetic_images_V2_REFINED')

# 3. Hardware & Constants
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
IMG_SIZE = 512
BATCH_SIZE = 16 # A100 can handle 4-8 easily at 512px

# 4. Check Directory Integrity
for path in [REAL_DATA_DIR, SYNTH_INPUT_DIR]:
    if not os.path.exists(path):
        print(f"❌ ERROR: Path not found: {path}")
    else:
        file_count = len([f for f in os.listdir(path) if not f.endswith('_mask.png')])
        print(f"✅ Found {file_count} images in {os.path.basename(path)}")

os.makedirs(REFINED_OUT_DIR, exist_ok=True)
print(f"🚀 Running on: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

class CHANADomainDataset(Dataset):
    def __init__(self, synth_dir, real_dir, transform=None):
        # Explicitly filter out masks to focus on image translation
        self.synth_paths = sorted([
            os.path.join(synth_dir, f) for f in os.listdir(synth_dir)
            if f.endswith(('.png', '.jpg', '.tif')) and '_mask' not in f
        ])
        self.real_paths = sorted([
            os.path.join(real_dir, f) for f in os.listdir(real_dir)
            if f.endswith(('.png', '.jpg', '.tif'))
        ])
        self.transform = transform

    def __len__(self): return len(self.synth_paths)

    def __getitem__(self, idx):
        synth_img = Image.open(self.synth_paths[idx]).convert('RGB')
        # Unpaired training: pick a random real image to learn the domain from
        real_img = Image.open(np.random.choice(self.real_paths)).convert('RGB')

        if self.transform:
            synth_img = self.transform(synth_img)
            real_img = self.transform(real_img)
        return synth_img, real_img

# Standard GAN Transforms (TanH normalization [-1, 1])
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

dataset = CHANADomainDataset(SYNTH_INPUT_DIR, REAL_DATA_DIR, transform=transform)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# --- SANITY CHECK ---
s_sample, r_sample = next(iter(dataloader))
print(f"📦 Batch Tensors: Synth={s_sample.shape} | Real={r_sample.shape}")

def calc_mean_std(feat, eps=1e-5):
    size = feat.size()
    N, C = size[:2]
    feat_var = feat.view(N, C, -1).var(dim=2) + eps
    feat_std = feat_var.sqrt().view(N, C, 1, 1)
    feat_mean = feat.view(N, C, -1).mean(dim=2).view(N, C, 1, 1)
    return feat_mean, feat_std

def adain_color_fix(content_feat, style_feat):
    """Matches Synthetic global statistics to Real data."""
    size = content_feat.size()
    style_mean, style_std = calc_mean_std(style_feat)
    content_mean, content_std = calc_mean_std(content_feat)
    normalized_feat = (content_feat - content_mean.expand(size)) / content_std.expand(size)
    return normalized_feat * style_std.expand(size) + style_mean.expand(size)

# --- VISUAL VALIDATION: STAGE 1 ---
def denorm(t): return (t.cpu().squeeze().permute(1, 2, 0).numpy() * 0.5 + 0.5).clip(0, 1)

s_batch, r_batch = next(iter(dataloader))
adain_out = adain_color_fix(s_batch, r_batch)

plt.figure(figsize=(15, 5))
titles = ["Raw Synthetic", "Real Reference", "AdaIN Corrected"]
imgs = [denorm(s_batch[0]), denorm(r_batch[0]), denorm(adain_out[0])]

for i, (img, title) in enumerate(zip(imgs, titles)):
    plt.subplot(1, 3, i+1); plt.imshow(img); plt.title(title); plt.axis('off')
plt.show()

# Histogram Comparison
plt.figure(figsize=(10, 4))
sns.kdeplot(imgs[0].flatten(), color='red', label='Synthetic (Pre-Fix)')
sns.kdeplot(imgs[1].flatten(), color='blue', label='Real Lab Target')
sns.kdeplot(imgs[2].flatten(), color='green', label='AdaIN Result', ls='--')
plt.title("Statistical Domain Alignment (Pixel Intensity)")
plt.legend(); plt.show()

"""### Save AdaIN Visualization Data to CSV

The pixel intensity data used for the histogram comparison in the AdaIN visualization has been saved to a CSV file. You can find it in your Google Drive.
"""

import pandas as pd
from google.colab import files
import os
from torch.utils.data import DataLoader, Dataset # Added Dataset and DataLoader imports
from torchvision import transforms # Added transforms import
from PIL import Image # Added Image import
import numpy as np # Added numpy import

# Re-define necessary components for dataloader to ensure it's always available
class CHANADomainDataset(Dataset):
    def __init__(self, synth_dir, real_dir, transform=None):
        self.synth_paths = sorted([
            os.path.join(synth_dir, f) for f in os.listdir(synth_dir)
            if f.endswith(('.png', '.jpg', '.tif')) and '_mask' not in f
        ])
        self.real_paths = sorted([
            os.path.join(real_dir, f) for f in os.listdir(real_dir)
            if f.endswith(('.png', '.jpg', '.tif'))
        ])
        self.transform = transform

    def __len__(self): return len(self.synth_paths)

    def __getitem__(self, idx):
        synth_img = Image.open(self.synth_paths[idx]).convert('RGB')
        real_img = Image.open(np.random.choice(self.real_paths)).convert('RGB')

        if self.transform:
            synth_img = self.transform(synth_img)
            real_img = self.transform(real_img)
        return synth_img, real_img

# Standard GAN Transforms (TanH normalization [-1, 1])
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

dataset = CHANADomainDataset(SYNTH_INPUT_DIR, REAL_DATA_DIR, transform=transform)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# Original code to generate AdaIN data
s_batch, r_batch = next(iter(dataloader))
adain_out = adain_color_fix(s_batch, r_batch)

def denorm(t): return (t.cpu().squeeze().permute(1, 2, 0).numpy() * 0.5 + 0.5).clip(0, 1)

imgs_for_csv = [denorm(s_batch[0]), denorm(r_batch[0]), denorm(adain_out[0])]

# Flatten the pixel intensity data for each image type
raw_synth_intensity = imgs_for_csv[0].flatten()
real_ref_intensity = imgs_for_csv[1].flatten()
adain_corrected_intensity = imgs_for_csv[2].flatten()

# Create a dictionary for the DataFrame. Since all images are the same size, their flattened arrays will have the same length.
adain_data = pd.DataFrame({
    'Raw_Synthetic_Pixel_Intensity': raw_synth_intensity,
    'Real_Reference_Pixel_Intensity': real_ref_intensity,
    'AdaIN_Corrected_Pixel_Intensity': adain_corrected_intensity
})

# Define the path to save the CSV in Google Drive
adain_csv_path = os.path.join(DRIVE_BASE, 'adain_pixel_intensity_data.csv')

# Save the DataFrame to a CSV file
adain_data.to_csv(adain_csv_path, index=False)

print(f"AdaIN pixel intensity data saved to: {adain_csv_path}")
print(f"\n--- Download Link ---")
print(f"You can find the file at {adain_csv_path} in your Google Drive.")

class ResNetBlock(nn.Module):
    def __init__(self, dim):
        super(ResNetBlock, self).__init__()
        self.conv_block = nn.Sequential(
            nn.ReflectionPad2d(1), nn.Conv2d(dim, dim, 3), nn.InstanceNorm2d(dim), nn.ReLU(True),
            nn.ReflectionPad2d(1), nn.Conv2d(dim, dim, 3), nn.InstanceNorm2d(dim)
        )
    def forward(self, x): return x + self.conv_block(x)

class ResNetGenerator(nn.Module):
    def __init__(self, input_nc=3, output_nc=3, ngf=64, n_blocks=9):
        super(ResNetGenerator, self).__init__()
        model = [nn.ReflectionPad2d(3), nn.Conv2d(input_nc, ngf, 7), nn.InstanceNorm2d(ngf), nn.ReLU(True)]
        # Downsampling
        for i in range(2):
            mult = 2**i
            model += [nn.Conv2d(ngf * mult, ngf * mult * 2, 3, stride=2, padding=1),
                      nn.InstanceNorm2d(ngf * mult * 2), nn.ReLU(True)]
        # Residual blocks (Preserves shape)
        for i in range(n_blocks): model += [ResNetBlock(ngf * 4)]
        # Upsampling
        for i in range(2):
            mult = 2**(2 - i)
            model += [nn.ConvTranspose2d(ngf * mult, int(ngf * mult / 2), 3, stride=2, padding=1, output_padding=1),
                      nn.InstanceNorm2d(int(ngf * mult / 2)), nn.ReLU(True)]
        model += [nn.ReflectionPad2d(3), nn.Conv2d(ngf, output_nc, 7), nn.Tanh()]
        self.model = nn.Sequential(*model)
    def forward(self, x): return self.model(x)

# Initialize
G_S2R = ResNetGenerator().to(DEVICE)
print("✅ Generator Architecture Loaded.")

import time
import pandas as pd
import os

# Optimizers & Loss
# The Discriminator: Judges if a texture looks like a real lab slide
D_R = nn.Sequential(
    nn.Conv2d(3, 64, 4, stride=2, padding=1),
    nn.InstanceNorm2d(64),
    nn.LeakyReLU(0.2, inplace=True),
    nn.Conv2d(64, 128, 4, stride=2, padding=1),
    nn.InstanceNorm2d(128),
    nn.LeakyReLU(0.2, inplace=True),
    nn.Conv2d(128, 256, 4, stride=2, padding=1),
    nn.InstanceNorm2d(256),
    nn.LeakyReLU(0.2, inplace=True),
    nn.Conv2d(256, 1, 4, padding=1) # Output 1 map
).to(DEVICE)

optimizer_D = optim.Adam(D_R.parameters(), lr=0.0001, betas=(0.5, 0.999))
optimizer_G = optim.Adam(G_S2R.parameters(), lr=0.0002, betas=(0.5, 0.999))
criterion_GAN = nn.MSELoss()
criterion_Id = nn.L1Loss() # Identity loss to prevent shape morphing

# --- TRAINING LOOP ---
EPOCHS = 10

def validate_refinement(synth_tensor, real_tensor, generator):
    """Visualizes the domain alignment progress."""
    generator.eval()
    with torch.no_grad():
        # Apply AdaIN then Generator
        guided = adain_color_fix(synth_tensor.to(DEVICE), real_tensor.to(DEVICE))
        refined = generator(guided)

    def denorm(t): return (t.cpu().squeeze().permute(1, 2, 0).numpy() * 0.5 + 0.5).clip(0, 1)

    plt.figure(figsize=(20, 5))
    titles = ["1. Raw Synth", "2. AdaIN Corrected", "3. GAN Refined", "4. Real Target"]
    # Show first item in batch
    imgs = [denorm(synth_tensor[0]), denorm(guided[0]), denorm(refined[0]), denorm(real_tensor[0])]

    for i, (img, title) in enumerate(zip(imgs, titles)):
        plt.subplot(1, 4, i+1); plt.imshow(img); plt.title(title); plt.axis('off')
    plt.tight_layout(); plt.show()

# Lists to store metrics
epoch_g_losses = []
epoch_d_losses = []

for epoch in range(EPOCHS):
    pbar = tqdm(dataloader, desc=f"Epoch {epoch+1}")

    current_g_losses = []
    current_d_losses = []

    for i, (synth, real) in enumerate(pbar):
        synth, real = synth.to(DEVICE), real.to(DEVICE)

        # --- TRAIN GENERATOR ---
        optimizer_G.zero_grad()
        synth_guided = adain_color_fix(synth, real)
        refined = G_S2R(synth_guided)

        # Identity: Keep the AdaIN color/shape
        loss_id = criterion_Id(refined, synth_guided) * 15.0
        # GAN: Try to fool the discriminator
        pred_fake = D_R(refined)
        loss_GAN = criterion_GAN(pred_fake, torch.ones_like(pred_fake))

        g_loss = loss_GAN + loss_id
        g_loss.backward()
        optimizer_G.step()
        current_g_losses.append(g_loss.item())

        # --- TRAIN DISCRIMINATOR ---
        optimizer_D.zero_grad()
        # Real loss
        pred_real = D_R(real)
        loss_real = criterion_GAN(pred_real, torch.ones_like(pred_real))
        # Fake loss
        pred_fake = D_R(refined.detach())
        loss_fake = criterion_GAN(pred_fake, torch.zeros_like(pred_fake))

        d_loss = (loss_real + loss_fake) * 0.5
        d_loss.backward()
        optimizer_D.step()
        current_d_losses.append(d_loss.item())

        pbar.set_postfix({"G": g_loss.item(), "D": d_loss.item()})

    # Store mean loss for the epoch
    epoch_g_losses.append(sum(current_g_losses) / len(current_g_losses))
    epoch_d_losses.append(sum(current_d_losses) / len(current_d_losses))

    validate_refinement(synth, real, G_S2R)

# Create a DataFrame from the collected losses
training_metrics_df = pd.DataFrame({
    'Epoch': range(1, EPOCHS + 1),
    'Generator_Loss': epoch_g_losses,
    'Discriminator_Loss': epoch_d_losses
})

# Define the path to save the CSV in Google Drive
training_metrics_csv_path = os.path.join(DRIVE_BASE, 'gan_training_metrics.csv')

# Save the DataFrame to a CSV file
training_metrics_df.to_csv(training_metrics_csv_path, index=False)

print(f"\nGAN training metrics saved to: {training_metrics_csv_path}")
print(f"You can find the file at {training_metrics_csv_path} in your Google Drive.")

import pandas as pd
import os

# Define the path where the training metrics CSV was saved
training_metrics_csv_path = os.path.join(DRIVE_BASE, 'gan_training_metrics.csv')

# Load the CSV into a DataFrame
if os.path.exists(training_metrics_csv_path):
    loaded_training_metrics_df = pd.read_csv(training_metrics_csv_path)
    print(f"Successfully loaded training metrics from: {training_metrics_csv_path}")
    display(loaded_training_metrics_df.head())
else:
    print(f"Error: Training metrics CSV not found at {training_metrics_csv_path}")
    print("Please ensure the training loop in the previous cell was executed successfully.")

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure the DataFrame exists from the previous cell
if 'loaded_training_metrics_df' in locals() and not loaded_training_metrics_df.empty:
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=loaded_training_metrics_df, x='Epoch', y='Generator_Loss', label='Generator Loss', marker='o')
    sns.lineplot(data=loaded_training_metrics_df, x='Epoch', y='Discriminator_Loss', label='Discriminator Loss', marker='x')

    plt.title('GAN Training Loss Over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.grid(True)
    plt.legend()
    plt.show()
else:
    print("Training metrics DataFrame not found or is empty. Please run the previous cells to load the data.")

import seaborn as sns

def run_final_forensics(generator, dataloader):
    generator.eval()
    synth_batch, real_batch = next(iter(dataloader))

    with torch.no_grad():
        # Apply the full refinement pipeline
        guided = adain_color_fix(synth_batch.to(DEVICE), real_batch.to(DEVICE))
        refined = generator(guided)

    def denorm(t): return (t.cpu().squeeze().permute(1, 2, 0).numpy() * 0.5 + 0.5).clip(0, 1)

    # 1. Visual Comparison
    plt.figure(figsize=(20, 5))
    titles = ["Raw Synthetic", "AdaIN Fix", "GAN Refined (V2)", "Real Lab Reference"]
    imgs = [denorm(synth_batch[0]), denorm(guided[0]), denorm(refined[0]), denorm(real_batch[0])]
    for i, (img, title) in enumerate(zip(imgs, titles)):
        plt.subplot(1, 4, i+1); plt.imshow(img); plt.title(title); plt.axis('off')
    plt.show()

    # 2. Histogram Alignment (The crucial part)
    plt.figure(figsize=(12, 6))
    # Flatten pixels for intensity distribution
    sns.kdeplot(imgs[0].flatten(), color='red', label='V1: Raw Synthetic', alpha=0.6)
    sns.kdeplot(imgs[2].flatten(), color='green', label='V2: Refined Synthetic', lw=3)
    sns.kdeplot(imgs[3].flatten(), color='blue', label='Real Lab Target', lw=2, ls='--')

    plt.title("CHANA Domain Alignment: Pixel Intensity Distribution", fontsize=14, fontweight='bold')
    plt.xlabel("Normalized Brightness (0.0=Black, 1.0=White)")
    plt.ylabel("Density")
    plt.legend()
    plt.grid(alpha=0.2)
    plt.show()

# Execute
run_final_forensics(G_S2R, dataloader)

import time

def generate_forensics_subset(generator, dataloader, num_samples=100):
    generator.eval()
    print(f"📂 Generating {num_samples} Refined V2 samples for analysis...")

    start_time = time.time()
    count = 0
    with torch.no_grad():
        for synth_batch, real_batch in tqdm(dataloader, desc="Refining"):
            if count >= num_samples: break

            synth_batch = synth_batch.to(DEVICE)
            real_batch = real_batch.to(DEVICE)

            # Apply the full pipeline: AdaIN -> Generator
            refined = generator(adain_color_fix(synth_batch, real_batch))

            for i in range(refined.size(0)):
                if count >= num_samples: break
                # Convert to BGR for OpenCV saving
                img = (refined[i].cpu().permute(1, 2, 0).numpy() * 0.5 + 0.5) * 255
                img = cv2.cvtColor(img.clip(0, 255).astype(np.uint8), cv2.COLOR_RGB2BGR)

                out_path = os.path.join(REFINED_OUT_DIR, f"forensics_v2_{count:03d}.png")
                cv2.imwrite(out_path, img)
                count += 1

    print(f"✅ Subset Ready in {REFINED_OUT_DIR}. Time: {time.time() - start_time:.2f}s")

# Run this once to ensure the metrics have data to read
generate_forensics_subset(G_S2R, dataloader, num_samples=100)

from torchvision import models

def extract_features_for_forensics(folder_path, num_samples=100):
    """Maps a folder to a latent manifold using ResNet50."""
    model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1).to(DEVICE)
    model = nn.Sequential(*list(model.children())[:-1]) # Remove classification layer
    model.eval()

    preprocess = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    # Filter for images, avoiding masks
    paths = sorted([os.path.join(folder_path, f) for f in os.listdir(folder_path)
                    if f.endswith(('.png', '.jpg')) and '_mask' not in f])[:num_samples]

    features = []
    start_time = time.time()
    with torch.no_grad():
        for p in tqdm(paths, desc=f"Scanning {os.path.basename(folder_path)}"):
            img = Image.open(p).convert('RGB')
            tensor = preprocess(img).unsqueeze(0).to(DEVICE)
            features.append(model(tensor).cpu().numpy().flatten())

    print(f"✅ Features extracted. Time: {time.time() - start_time:.2f}s")
    return np.array(features)

print("🧪 Profiling Domains...")
f_real = extract_features_for_forensics(REAL_DATA_DIR, 100)
f_v1   = extract_features_for_forensics(SYNTH_INPUT_DIR, 100)
f_v2   = extract_features_for_forensics(REFINED_OUT_DIR, 100)

!pip install -q umap-learn
import umap
from scipy.linalg import sqrtm

def calculate_fid(act1, act2):
    """Fréchet Inception Distance calculation."""
    mu1, sigma1 = act1.mean(axis=0), np.cov(act1, rowvar=False)
    mu2, sigma2 = act2.mean(axis=0), np.cov(act2, rowvar=False)
    ssdiff = np.sum((mu1 - mu2)**2.0)
    covmean = sqrtm(sigma1.dot(sigma2))
    if np.iscomplexobj(covmean): covmean = covmean.real
    return ssdiff + np.trace(sigma1 + sigma2 - 2.0 * covmean)

# 1. Compute UMAP Projection
combined = np.concatenate([f_real, f_v1, f_v2])
labels = (['Real Data'] * 100 + ['V1: Diffusion'] * 100 + ['V2: Refined'] * 100)

print("⏳ Computing UMAP Manifold...")
start = time.time()
reducer = umap.UMAP(n_neighbors=15, min_dist=0.1, random_state=42)
embedding = reducer.fit_transform(combined)

plt.figure(figsize=(10, 7))
sns.scatterplot(x=embedding[:, 0], y=embedding[:, 1], hue=labels, palette='viridis', s=70, alpha=0.8)
plt.title("CHANA Domain Manifold Alignment (N=300 Total Samples)", fontweight='bold')
plt.show()

# 2. Output Distance Metrics
print(f"📊 FID (Real vs V1 Synthetic): {calculate_fid(f_real, f_v1):.2f}")
print(f"📊 FID (Real vs V2 Refined):   {calculate_fid(f_real, f_v2):.2f}")
print(f"✅ Completion Time: {time.time() - start:.2f}s")

from skimage.metrics import structural_similarity as ssim

def get_radial_psd(folder_path, num_samples=50):
    psds = []
    paths = sorted([os.path.join(folder_path, f) for f in os.listdir(folder_path)
                    if f.endswith(('.png', '.jpg')) and '_mask' not in f])[:num_samples]
    for p in paths:
        img = cv2.imread(p, 0)
        f_shift = np.fft.fftshift(np.fft.fft2(cv2.resize(img, (512, 512))))
        mag = 20 * np.log(np.abs(f_shift) + 1e-9)
        h, w = mag.shape
        y, x = np.indices((h, w))
        r = np.sqrt((x - w//2)**2 + (y - h//2)**2).astype(int)
        psds.append((np.bincount(r.ravel(), mag.ravel()) / np.bincount(r.ravel()))[:250])
    return np.mean(psds, axis=0)

# 1. FFT Frequency Check
print("🌊 Analyzing Frequency Signatures...")
psd_real, psd_v1, psd_v2 = [get_radial_psd(d) for d in [REAL_DATA_DIR, SYNTH_INPUT_DIR, REFINED_OUT_DIR]]

plt.figure(figsize=(8, 5))
plt.plot(psd_real, label='Real (Target)', color='blue', ls='--', lw=2)
plt.plot(psd_v1, label='V1 (Smooth Diffusion)', color='red', alpha=0.5)
plt.plot(psd_v2, label='V2 (Textured GAN)', color='green', lw=2)
plt.title("Spectral Density: Microscope Grain Matching")
plt.legend(); plt.grid(alpha=0.3); plt.show()

# 2. SSIM Geometry Check (Fixed Import)
paths_v1 = sorted([os.path.join(SYNTH_INPUT_DIR, f) for f in os.listdir(SYNTH_INPUT_DIR) if '_mask' not in f])[:20]
paths_v2 = sorted([os.path.join(REFINED_OUT_DIR, f) for f in os.listdir(REFINED_OUT_DIR)])[:20]
ssim_vals = [ssim(cv2.imread(p1, 0), cv2.imread(p2, 0)) for p1, p2 in zip(paths_v1, paths_v2)]

print(f"🛡️ Structural Integrity (SSIM V1 vs V2): {np.mean(ssim_vals):.4f}")
print("   (Target > 0.95: Proves texture added without moving cell boundaries)")

"""### Download Data as CSV

Here's the data used for the UMAP manifold visualization and the spectral density plots, saved as CSV files. You can download them using the links below.
"""

import pandas as pd
from google.colab import files

# --- UMAP Embedding Data ---
umap_df = pd.DataFrame(embedding, columns=['UMAP_Dim_1', 'UMAP_Dim_2'])
umap_df['Label'] = labels
umap_csv_path = os.path.join(DRIVE_BASE, 'umap_embedding_data.csv')
umap_df.to_csv(umap_csv_path, index=False)
print(f"UMAP embedding data saved to: {umap_csv_path}")

# --- Spectral Density Data ---
# The length of psd_real, psd_v1, psd_v2 might be different from the value 250 in get_radial_psd, use min_len for consistency.
min_len = min(len(psd_real), len(psd_v1), len(psd_v2))
spectral_df = pd.DataFrame({
    'Radial_Frequency_Bin': range(min_len),
    'Real_Target_PSD': psd_real[:min_len],
    'V1_Smooth_Diffusion_PSD': psd_v1[:min_len],
    'V2_Textured_GAN_PSD': psd_v2[:min_len]
})
spectral_csv_path = os.path.join(DRIVE_BASE, 'spectral_density_data.csv')
spectral_df.to_csv(spectral_csv_path, index=False)
print(f"Spectral density data saved to: {spectral_csv_path}")


print("\n--- Download Links ---")
# Provide download links for UMAP data
#files.download(umap_csv_path) # This automatically downloads, which might not be desired for multiple files.
print(f"UMAP Embedding Data: You can find the file at {umap_csv_path} in your Google Drive.")

# Provide download links for Spectral Density data
#files.download(spectral_csv_path)
print(f"Spectral Density Data: You can find the file at {spectral_csv_path} in your Google Drive.")