# -*- coding: utf-8 -*-
"""CHANA TransUNet with Domains

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btu3KgcgUgpZPv34T935x6nRPKlInTk8

## CHANA TransUNet

A 3 phase domain adaptation implementation on a TransUNet architecture including 1. diffusionn based synthetic images 2. copy paste augmentation and 3. real data that is expert labelled. Total dataset size should be around 6.5k images.
"""

# CELL 1: ENVIRONMENT & IMPORTS
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations

import os
# Force float32 for stability
os.environ["SM_FRAMEWORK"] = "tf.keras"
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, Model, Input
from tensorflow.keras import mixed_precision
import segmentation_models as sm
import seaborn as sns
import pandas as pd
from skimage import io, measure, morphology
from scipy import ndimage
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve, average_precision_score
import gc

# Mount Drive
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- GLOBAL STABILITY SETTINGS ---
tf.config.experimental.enable_tensor_float_32_execution(True)
mixed_precision.set_global_policy('float32')
print(f"✅ TensorFlow {tf.__version__} Ready. Global Policy: Float32")

# CELL 2: CONFIGURATION & CURRICULUM (FINAL PATHS)
PROJECT_BASE_PATH = '/content/drive/MyDrive/CHANA_files'

# --- PATHS ---
# 1. Real Data (Gold Standard)
PREPROCESSED_IMAGES_DIR = os.path.join(PROJECT_BASE_PATH, 'preprocessed_rgb')
GROUND_TRUTH_MASKS_DIR = os.path.join(PROJECT_BASE_PATH, 'mask_images_512')

# 2. Synthetic Data Sources
DIFFUSION_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_training_data_v2_ancestral')
# Copy-Paste: Point to IMAGE folder; script finds masks in sibling 'generated_masks'
COPYPASTE_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_experiment/generated_images')
# Pseudo-Labels: Point to IMAGE folder; script finds masks in sibling 'masks'
PSEUDO_DIR = os.path.join(PROJECT_BASE_PATH, 'pseudo_train_data', 'images')

# --- 📅 THE CURRICULUM SCHEDULE V8.0 ---
CURRICULUM_PLAN = [
    {
        "stage": 1,
        "name": "Phase 1: Diffusion Pretraining",
        "description": "Learning Spatial Semantics & Shapes",
        "data_dir": DIFFUSION_DIR,
        "data_type": "diffusion",
        "epochs": 40,
        "init_lr": 1e-4,
        "loss_strategy": "robust", # Focal Tversky (Hard shapes)
        "save_path": os.path.join(PROJECT_BASE_PATH, 'transunet_v8_stage1_diffusion.weights.h5')
    },
    {
        "stage": 2,
        "name": "Phase 2: Copy-Paste Bridging",
        "description": "Learning Object Permanence & Texture",
        "data_dir": COPYPASTE_DIR,
        "data_type": "copypaste",
        "epochs": 80,
        "init_lr": 5e-5,
        "loss_strategy": "robust", # Focal Tversky (Hard boundaries)
        "save_path": os.path.join(PROJECT_BASE_PATH, 'transunet_v8_stage2_copypaste.weights.h5')
    },
    {
        "stage": 2.5,
        "name": "Phase 2.5: Noisy Student (Pseudo-Labels)",
        "description": "Bridge Phase: Real Texture / Noisy Labels",
        "data_dir": PSEUDO_DIR,
        "data_type": "pseudo",
        "epochs": 50,
        "init_lr": 2e-5, # Lower LR to avoid overfitting noise
        "loss_strategy": "soft", # BCE + Label Smoothing (Cures Arrogance)
        "save_path": os.path.join(PROJECT_BASE_PATH, 'transunet_v8_stage2.5_pseudo.weights.h5')
    },
    {
        "stage": 3,
        "name": "Phase 3: Real Fine-Tuning",
        "description": "Domain Adaptation & Precision",
        "data_dir": PREPROCESSED_IMAGES_DIR, # Will use Train Split
        "data_type": "real",
        "epochs": 200,
        "init_lr": 1e-5, # Surgical fine-tuning
        "loss_strategy": "robust", # Back to Focal Tversky for precision
        "save_path": os.path.join(PROJECT_BASE_PATH, 'transunet_v8_stage3_real_finetune.weights.h5')
    }
]

# Config
IMG_HEIGHT, IMG_WIDTH = 512, 512
IMG_CHANNELS = 3
NUM_CLASSES = 1
BATCH_SIZE = 16

print("🚀 AUTOMATED CURRICULUM CONFIGURED (V8.0).")

# CELL 3: DATA LOADING UTILITIES
import albumentations as A

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def preprocess_input_v7(img):
    img = img.astype(np.float32) / 255.0
    img = (img - IMAGENET_MEAN) / IMAGENET_STD
    return img

aug_pipeline = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=20, p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.CoarseDropout(max_holes=6, max_height=24, max_width=24, p=0.3),
])

def augment_data(img, mask):
    aug = aug_pipeline(image=img, mask=mask)
    return aug['image'], aug['mask']

def load_and_process(img_path, mask_path):
    path_str = img_path.decode('utf-8')
    try:
        img = cv2.imread(path_str, cv2.IMREAD_COLOR)
        if img is None: # Fallback for TIF/Special formats
            img = io.imread(path_str)
            if img.ndim == 2: img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
            elif img.shape[2] == 4: img = img[:,:,:3]
    except:
        return np.zeros((512,512,3), dtype=np.float32), np.zeros((512,512,1), dtype=np.float32)

    if img is not None:
        if path_str.lower().endswith(('.png', '.jpg')):
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img, (512, 512), interpolation=cv2.INTER_AREA)
    img = preprocess_input_v7(img)

    m_path_str = mask_path.decode('utf-8')
    if m_path_str.endswith('.tif'): mask = io.imread(m_path_str)
    else: mask = cv2.imread(m_path_str, cv2.IMREAD_GRAYSCALE)
    if mask is None: mask = io.imread(m_path_str)

    if mask.shape[:2] != (512, 512):
        mask = cv2.resize(mask, (512, 512), interpolation=cv2.INTER_NEAREST)

    mask = (mask > 0).astype(np.float32)
    if mask.ndim == 2: mask = np.expand_dims(mask, axis=-1)

    return img, mask

def create_tf_dataset(images, masks, training=True):
    ds = tf.data.Dataset.from_tensor_slices((images, masks))
    ds = ds.shuffle(len(images)) if training else ds
    ds = ds.repeat()

    ds = ds.map(lambda i, m: tf.numpy_function(load_and_process, [i, m], [tf.float32, tf.float32]),
                num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.map(lambda i, m: tf.numpy_function(augment_data, [i, m], [tf.float32, tf.float32]),
                    num_parallel_calls=tf.data.AUTOTUNE)

    # TransUNet expects 3 outputs (Main, Aux1, Aux2) for Deep Supervision
    def format_output(i, m):
        i = tf.ensure_shape(i, [512, 512, 3])
        m = tf.ensure_shape(m, [512, 512, 1])
        m_64 = tf.image.resize(m, (64, 64), method='nearest')
        m_128 = tf.image.resize(m, (128, 128), method='nearest')
        return i, (m, m_64, m_128)

    ds = ds.map(format_output, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

# CELL 4: ARCHITECTURE (TransUNet V7.2 - UNCHANGED)
import tensorflow.keras.applications as applications

BACKBONE_NAME = 'efficientnetb0'
PRETRAINED_WEIGHTS = 'imagenet'
GROUPS = 8

class AddPositionEmbedding(layers.Layer):
    def __init__(self, transformer_dim, max_len=65536, **kwargs):
        super().__init__(**kwargs)
        self.transformer_dim = transformer_dim
        self.pos_embedding = layers.Embedding(input_dim=max_len, output_dim=transformer_dim)

    def call(self, x):
        seq_len = tf.shape(x)[1]
        positions = tf.range(start=0, limit=seq_len, delta=1)
        return x + self.pos_embedding(positions)

def build_transformer_bottleneck(input_tensor, transformer_dim=384, num_heads=6, num_layers=2, output_filters=512):
    x = layers.Conv2D(transformer_dim, (1, 1), padding='same', kernel_initializer='he_normal')(input_tensor)
    x = layers.GroupNormalization(groups=GROUPS)(x)
    patch_seq = layers.Reshape((input_tensor.shape[1] * input_tensor.shape[2], transformer_dim))(x)
    x = AddPositionEmbedding(transformer_dim)(patch_seq)

    for _ in range(num_layers):
        attn_output = layers.MultiHeadAttention(num_heads=num_heads, key_dim=transformer_dim // num_heads, dropout=0.1)(x, x)
        x = layers.Add()([x, attn_output])
        x = layers.LayerNormalization(epsilon=1e-6)(x)
        ffn_output = layers.Dense(transformer_dim * 4, activation='relu')(x)
        ffn_output = layers.Dense(transformer_dim)(ffn_output)
        x = layers.Add()([x, ffn_output])
        x = layers.LayerNormalization(epsilon=1e-6)(x)

    bottleneck_features = layers.Reshape((input_tensor.shape[1], input_tensor.shape[2], transformer_dim))(x)
    output = layers.Conv2D(output_filters, (1, 1), padding='same', activation='relu', kernel_initializer='he_normal')(bottleneck_features)
    output = layers.GroupNormalization(groups=GROUPS)(output)
    return output

def decoder_block(input_tensor, concat_tensor, num_filters):
    x = layers.Conv2DTranspose(num_filters, (2, 2), strides=(2, 2), padding='same')(input_tensor)

    def robust_resize(args):
        img, target = args
        target_shape = tf.shape(target)[1:3]
        return tf.image.resize(img, target_shape)

    x = layers.Lambda(robust_resize)([x, concat_tensor])
    x = layers.concatenate([x, concat_tensor], axis=-1)

    x = layers.Conv2D(num_filters, (3, 3), padding='same', kernel_initializer='he_normal')(x)
    x = layers.GroupNormalization(groups=GROUPS)(x); x = layers.Activation('relu')(x)
    x = layers.Conv2D(num_filters, (3, 3), padding='same', kernel_initializer='he_normal')(x)
    x = layers.GroupNormalization(groups=GROUPS)(x); x = layers.Activation('relu')(x)
    return x

def build_custom_unet(input_shape, num_classes):
    inputs = Input(shape=input_shape)
    backbone = applications.EfficientNetB0(weights=PRETRAINED_WEIGHTS, include_top=False, input_tensor=inputs)

    backbone.trainable = False
    for layer in backbone.layers:
        if isinstance(layer, layers.BatchNormalization): layer.trainable = True

    s1 = backbone.get_layer('block2a_expand_activation').output
    s2 = backbone.get_layer('block3a_expand_activation').output
    s3 = backbone.get_layer('block4a_expand_activation').output
    s4 = backbone.get_layer('block6a_expand_activation').output
    bridge = backbone.get_layer('top_activation').output

    trans_bottleneck = build_transformer_bottleneck(bridge)

    d1 = decoder_block(trans_bottleneck, s4, 512)
    d2 = decoder_block(d1, s3, 256)
    ds1 = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', name='aux1', dtype='float32')(d2)

    d3 = decoder_block(d2, s2, 128)
    ds2 = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', name='aux2', dtype='float32')(d3)

    d4 = decoder_block(d3, s1, 64)
    d5 = layers.Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(d4)
    d5 = layers.Conv2D(32, (3, 3), padding='same', activation='relu')(d5)

    outputs = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', dtype='float32', name='final')(d5)
    return Model(inputs=inputs, outputs=[outputs, ds1, ds2])

print("✅ Model Architecture Loaded.")

# CELL 5: DYNAMIC LOSS STRATEGIES
import tensorflow.keras.backend as K

# Strategy 1: "Robust" (Focal Tversky) - For Trusted Labels
def focal_tversky_loss(y_true, y_pred, alpha=0.3, beta=0.7, gamma=1.5):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    tp = K.sum(y_true_f * y_pred_f)
    fn = K.sum(y_true_f * (1 - y_pred_f))
    fp = K.sum((1 - y_true_f) * y_pred_f)
    tversky = (tp + 1e-6) / (tp + alpha * fn + beta * fp + 1e-6)
    return K.pow((1 - tversky), gamma)

# Strategy 2: "Soft" (BCE + Label Smoothing) - For Noisy Labels/Arrogant Models
def soft_bce_loss(y_true, y_pred):
    # Standard BCE with label smoothing (0.1 means target becomes 0.95/0.05)
    return tf.keras.losses.binary_crossentropy(y_true, y_pred, label_smoothing=0.1)

def dice_loss_fn(y_true, y_pred):
    smooth = 1e-6
    intersection = K.sum(y_true * y_pred)
    return 1 - (2. * intersection + smooth) / (K.sum(y_true) + K.sum(y_pred) + smooth)

common_metrics = [sm.metrics.iou_score, sm.metrics.f1_score]

# CELL 6: "THE VAULT" - STRICT DATA SPLITTING
print("🚜 Harvesting Real Data...")
all_real_img, all_real_mask = [], []

# 1. Harvest
for f in os.listdir(PREPROCESSED_IMAGES_DIR):
    if f.lower().endswith(('.png', '.tif', '.jpg')):
        base = os.path.splitext(f)[0]
        # Robust mask finding
        for ext in ['_mask.tif', '_mask.png', '.tif', '.png']:
            p = os.path.join(GROUND_TRUTH_MASKS_DIR, base + ext)
            if os.path.exists(p):
                all_real_img.append(os.path.join(PREPROCESSED_IMAGES_DIR, f))
                all_real_mask.append(p)
                break

# 2. Split 1: Isolate The Vault (15%)
remaining_img, vault_img, remaining_mask, vault_mask = train_test_split(
    all_real_img, all_real_mask, test_size=0.15, random_state=999 # Fixed seed
)

# 3. Split 2: Train vs Val (Validation 15% of original, approx 17% of remaining)
train_real_img, val_real_img, train_real_mask, val_real_mask = train_test_split(
    remaining_img, remaining_mask, test_size=0.176, random_state=42
)

print(f"🔒 THE VAULT (Test Set) Sealed: {len(vault_img)} images.")
print(f"📖 Validation Set Ready:       {len(val_real_img)} images.")
print(f"🏋️ Training Set Ready:         {len(train_real_img)} images.")

# Create the Validation Dataset ONCE for consistency
val_dataset = create_tf_dataset(val_real_img, val_real_mask, training=False)
STEPS_PER_EPOCH_VAL = len(val_real_img) // BATCH_SIZE

# Save Vault list
with open('VAULT_FILES.txt', 'w') as f:
    for item in vault_img: f.write(f"{item}\n")

# CELL 7: OBJECT-LEVEL METRICS CALLBACK (TRAINING MONITOR)
from tensorflow.keras.callbacks import Callback

class ObjectMetricsCallback(Callback):
    def __init__(self, val_images, val_masks, freq=1):
        super().__init__()
        self.val_images = val_images[:100] # Check first 100 for speed
        self.val_masks = val_masks[:100]
        self.freq = freq

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.freq != 0: return

        total_tp, total_fp, total_fn = 0, 0, 0
        min_area = 50

        # Run inference on subset
        for i, img_p in enumerate(self.val_images):
            try:
                # Load (Re-using helper)
                img, true_mask = load_and_process(img_p.encode('utf-8'), self.val_masks[i].encode('utf-8'))

                # Predict
                pred_prob = self.model.predict(np.expand_dims(img, 0), verbose=0)[0][0]

                # Threshold & Process
                p_mask = np.squeeze((pred_prob > 0.5).astype(np.uint8))
                p_mask = ndimage.binary_fill_holes(p_mask).astype(np.uint8)
                t_mask = np.squeeze((true_mask > 0.5).astype(np.uint8))

                # Count
                p_cents = [r.centroid for r in measure.regionprops(measure.label(p_mask)) if r.area > min_area]
                t_cents = [r.centroid for r in measure.regionprops(measure.label(t_mask)) if r.area > min_area]

                # Match
                matches = 0
                if t_cents and p_cents:
                    dists = cdist(t_cents, p_cents)
                    rows, cols = linear_sum_assignment(dists)
                    for r, c in zip(rows, cols):
                        if dists[r, c] < 25: matches += 1

                total_tp += matches
                total_fp += len(p_cents) - matches
                total_fn += len(t_cents) - matches
            except: pass

        # Calc Metrics
        prec = total_tp / (total_tp + total_fp + 1e-6)
        rec = total_tp / (total_tp + total_fn + 1e-6)
        f1 = 2 * prec * rec / (prec + rec + 1e-6)

        print(f"\n   🎯 [Epoch {epoch+1}] Object Metrics -> F1: {f1:.4f} | Prec: {prec:.4f} | Rec: {rec:.4f}")
        logs['val_object_f1'] = f1

# CELL 8: THE MASTER TRAINING LOOP (V8.0)
from tensorflow.keras.optimizers import AdamW

# 1. Initialize Model
tf.keras.backend.clear_session()
gc.collect()
model = build_custom_unet(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), num_classes=NUM_CLASSES)
print("🏗️ Model Initialized.")

# 2. Iterate Curriculum
for plan in CURRICULUM_PLAN:
    print(f"\n" + "="*60)
    print(f"🎬 STARTING {plan['name']}")
    print("="*60)

    # A. Dynamic Data Loading
    current_train_img, current_train_mask = [], []

    if plan['data_type'] == 'diffusion':
        for f in os.listdir(plan['data_dir']):
            if f.endswith('_image.png'):
                mask_p = os.path.join(plan['data_dir'], f.replace('_image.png', '_mask.png'))
                if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'copypaste':
        # Structure: .../synthetic_experiment/generated_images (plan['data_dir'])
        # Masks:     .../synthetic_experiment/generated_masks
        base_dir = os.path.dirname(plan['data_dir'])
        cp_mask_dir = os.path.join(base_dir, 'generated_masks')

        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg')):
                # Check for standard naming conventions
                possible_names = [f, f.replace('.png', '_mask.png'), f.replace('.jpg', '_mask.png')]
                for m_name in possible_names:
                    mask_p = os.path.join(cp_mask_dir, m_name)
                    if os.path.exists(mask_p):
                        current_train_img.append(os.path.join(plan['data_dir'], f))
                        current_train_mask.append(mask_p)
                        break

    elif plan['data_type'] == 'pseudo':
        # Structure: .../pseudo_train_data/images (plan['data_dir'])
        # Masks:     .../pseudo_train_data/masks
        base_dir = os.path.dirname(plan['data_dir'])
        pseudo_mask_dir = os.path.join(base_dir, 'masks')

        if not os.path.exists(pseudo_mask_dir):
             print(f"⚠️ WARNING: Pseudo mask dir not found at {pseudo_mask_dir}")

        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg', '.tif')):
                 # Try exact name match first
                 mask_p = os.path.join(pseudo_mask_dir, f)

                 # Fallback: check for _mask suffix
                 if not os.path.exists(mask_p):
                     name_no_ext = os.path.splitext(f)[0]
                     mask_p = os.path.join(pseudo_mask_dir, name_no_ext + "_mask.png")

                 # Fallback 2: Check for .tif if png missing
                 if not os.path.exists(mask_p):
                     mask_p = os.path.join(pseudo_mask_dir, os.path.splitext(f)[0] + ".tif")

                 if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'real':
        current_train_img = train_real_img
        current_train_mask = train_real_mask

    print(f"   -> Found {len(current_train_img)} training pairs.")

    if len(current_train_img) == 0:
        print(f"❌ CRITICAL ERROR: No data found for {plan['name']}. Check paths!")
        continue

    train_ds = create_tf_dataset(current_train_img, current_train_mask, training=True)
    steps_per_epoch = len(current_train_img) // BATCH_SIZE

    # B. Compile with Dynamic Loss & LR
    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=plan['init_lr'],
        decay_steps=plan['epochs'] * steps_per_epoch,
        alpha=0.05
    )
    optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

    # SELECT LOSS FUNCTION
    if plan['loss_strategy'] == 'soft':
        print("   -> Using SOFT Loss (BCE + Smoothing) for Noisy/Pseudo Data.")
        primary_loss = soft_bce_loss
        loss_weights = [1.0, 0.5, 0.5]
    else:
        print("   -> Using ROBUST Loss (Focal Tversky) for Clean/Real Data.")
        primary_loss = focal_tversky_loss
        loss_weights = [1.0, 0.3, 0.15]

    model.compile(
        optimizer=optimizer,
        loss=[primary_loss, dice_loss_fn, dice_loss_fn],
        loss_weights=loss_weights,
        metrics=[common_metrics, common_metrics, common_metrics]
    )

    # C. Callbacks
    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            plan['save_path'], monitor='val_final_iou_score', mode='max',
            save_best_only=True, save_weights_only=True, verbose=1
        ),
        ObjectMetricsCallback(val_real_img, val_real_mask, freq=2)
    ]

    if plan['stage'] == 3:
        callbacks.append(tf.keras.callbacks.EarlyStopping(
            monitor='val_final_iou_score', mode='max', patience=35, restore_best_weights=True, verbose=1
        ))

    # Define log path
    log_name = f"log_{plan['name'].replace(' ', '_')}_{os.path.basename(__file__)}.csv"
    callbacks.append(tf.keras.callbacks.CSVLogger(os.path.join(PROJECT_BASE_PATH, log_name)))


    # D. Train
    model.fit(
        train_ds,
        steps_per_epoch=steps_per_epoch,
        epochs=plan['epochs'],
        validation_data=val_dataset,
        validation_steps=STEPS_PER_EPOCH_VAL,
        callbacks=callbacks
    )

    # E. Handover
    print(f"✅ {plan['name']} Complete. Loading best weights...")
    model.load_weights(plan['save_path'])

print("\n🏆 DOMAIN ADAPTATION CURRICULUM COMPLETE.")

# CELL 9: "THE VAULT" PIXEL EVALUATION
print("⚖️ UNLOCKING THE VAULT: Final Evaluation...")

# 1. Load best weights from Phase 3
model.load_weights(os.path.join(PROJECT_BASE_PATH, 'transunet_v8_stage3_real_finetune.weights.h5'))

# 2. Run Inference on Vault
vault_metrics = []
print(f"   -> Processing {len(vault_img)} unseen test images...")

for i, img_path in enumerate(vault_img):
    try:
        # Load
        img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

        # Predict
        pred_prob = model.predict(np.expand_dims(img, 0), verbose=0)[0][0]

        # Pixel Metrics
        p_mask_bin = (pred_prob > 0.5).astype(np.float32)
        intersection = np.sum(true_mask * p_mask_bin)
        union = np.sum(true_mask) + np.sum(p_mask_bin) - intersection
        if np.sum(true_mask) == 0 and np.sum(p_mask_bin) == 0:
            iou = 1.0 # Perfect rejection
        else:
            iou = intersection / (union + 1e-6)

        vault_metrics.append({'path': img_path, 'iou': iou})

    except Exception as e: print(e)

df_vault = pd.DataFrame(vault_metrics)
print("\n" + "="*40)
print(f"🏛️ FINAL TEST SET (VAULT) REPORT")
print("="*40)
print(f"Mean IoU: {df_vault['iou'].mean():.4f}")
print("="*40)

# CELL 10: HUNGARIAN MATCHING & VISUALIZATION (RESTORED & UPDATED FOR VAULT)
print("\n--- Object-Level Evaluation (Vault) ---")

# --- CONFIG ---
MIN_AREA = 50
MAX_DISTANCE = 25
SAMPLE_LIMIT = 50 # How many to visualize/check

# --- DATA TARGETING ---
# Using VAULT (Test Set)
target_img_list = vault_img
target_mask_list = vault_mask

# --- HELPER: Plotting ---
def plot_object_detection(img, t_cents, p_cents, matches):
    display_img = np.clip(img * IMAGENET_STD + IMAGENET_MEAN, 0, 1)

    plt.figure(figsize=(8, 8))
    plt.imshow(display_img)

    # Truth (Blue)
    if len(t_cents) > 0:
        t_arr = np.array(t_cents)
        plt.plot(t_arr[:, 1], t_arr[:, 0], 'bo', markersize=10, fillstyle='none', markeredgewidth=2, label='Truth')

    # Pred (Red)
    if len(p_cents) > 0:
        p_arr = np.array(p_cents)
        plt.plot(p_arr[:, 1], p_arr[:, 0], 'rx', markersize=10, markeredgewidth=2, label='Pred')

    # Matches (Green)
    for t_idx, p_idx in matches:
        tr, tc = t_cents[t_idx]
        pr, pc = p_cents[p_idx]
        plt.plot([tc, pc], [tr, pr], 'g-', linewidth=2, alpha=0.7)

    plt.legend(loc='upper right')
    plt.title("Blue=Truth, Red=Pred, Green=Match")
    plt.axis('off')
    plt.show()

# --- EXECUTION ---
total_tp, total_fp, total_fn = 0, 0, 0

for i, img_path in enumerate(target_img_list[:SAMPLE_LIMIT]):
    try:
        # Load
        img, true_mask = load_and_process(img_path.encode('utf-8'), target_mask_list[i].encode('utf-8'))

        # Predict
        pred_prob = model.predict(np.expand_dims(img, 0), verbose=0)[0][0]

        # Process
        p_mask_2d = np.squeeze((pred_prob > 0.5).astype(np.uint8))
        t_mask_2d = np.squeeze((true_mask > 0.5).astype(np.uint8))
        p_mask_2d = ndimage.binary_fill_holes(p_mask_2d).astype(np.uint8)

        # Get Centroids
        p_props = measure.regionprops(measure.label(p_mask_2d))
        p_cents = [r.centroid for r in p_props if MIN_AREA < r.area < 10000]

        t_props = measure.regionprops(measure.label(t_mask_2d))
        t_cents = [r.centroid for r in t_props if MIN_AREA < r.area < 10000]

        # Match (Hungarian)
        matches = []
        tp_curr = 0

        if len(t_cents) > 0 and len(p_cents) > 0:
            t_arr = np.array(t_cents)
            p_arr = np.array(p_cents)
            dists = cdist(t_arr, p_arr)
            rows, cols = linear_sum_assignment(dists)

            for row, col in zip(rows, cols):
                if dists[row, col] < MAX_DISTANCE:
                    matches.append((row, col))
                    tp_curr += 1

        fp_curr = len(p_cents) - tp_curr
        fn_curr = len(t_cents) - tp_curr

        total_tp += tp_curr
        total_fp += fp_curr
        total_fn += fn_curr

        # Visualize first 3
        if i < 3 and (t_cents or p_cents):
            plot_object_detection(img, t_cents, p_cents, matches)

    except Exception as e: print(f"Skip: {e}")

# --- METRICS ---
precision = total_tp / (total_tp + total_fp + 1e-6)
recall = total_tp / (total_tp + total_fn + 1e-6)
f1 = 2 * precision * recall / (precision + recall + 1e-6)

print("\n" + "="*40)
print(f"🎯 OBJECT-LEVEL METRICS (VAULT)")
print("="*40)
print(f"Global F1 Score: {f1:.4f}")
print(f"Global Precision: {precision:.4f}")
print(f"Global Recall:    {recall:.4f}")
print("="*40)

# CELL 11: SIZE BIN ANALYSIS (RESTORED & UPDATED FOR VAULT)
print("--- Deep Diagnostics by Object Size (Vault) ---")

# --- CONFIG ---
SIZE_BINS = [0, 500, 1500, 10000]
BIN_LABELS = ['Small', 'Medium', 'Large']
object_data = []

# --- EXECUTION ---
if vault_img:
    for i, img_path in enumerate(vault_img[:100]): # Limit to 100 for speed
        try:
            img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))
            pred_prob = model.predict(np.expand_dims(img, 0), verbose=0)[0][0]
            p_mask = (pred_prob > 0.5).astype(np.uint8)
            t_mask = (true_mask > 0.5).astype(np.uint8)
            if t_mask.ndim == 3: t_mask = t_mask[:,:,0]

            true_labels = measure.label(t_mask, connectivity=2)
            for t_region in measure.regionprops(true_labels):
                if t_region.area < 50: continue

                t_mask_iso = (true_labels == t_region.label)
                intersection = np.logical_and(t_mask_iso, p_mask).sum()
                coverage = intersection / t_region.area

                object_data.append({
                    'Area': t_region.area,
                    'Detected': coverage > 0.5, # >50% overlap = Hit
                    'IoU': coverage
                })
        except: pass

    if object_data:
        obj_df = pd.DataFrame(object_data)
        obj_df['Size_Bin'] = pd.cut(obj_df['Area'], bins=SIZE_BINS, labels=BIN_LABELS)

        print("\nDetection Rate by Size:")
        print(obj_df.groupby('Size_Bin')['Detected'].mean())

        plt.figure(figsize=(8, 5))
        sns.barplot(data=obj_df, x='Size_Bin', y='Detected', palette='viridis')
        plt.title("Probability of Detecting a Cell vs. Cell Size")
        plt.ylabel("Detection Probability")
        plt.ylim(0, 1.0)
        plt.grid(axis='y', alpha=0.3)
        plt.show()
    else:
        print("No objects found to analyze.")

# CELL 12: THE "DEEP DIVE" DIAGNOSTIC (Vault Analytics & Interpretability)
# Run this AFTER loading the best weights in the previous cell.

import matplotlib.cm as cm
from sklearn.metrics import auc

print("🔬 STARTING DEEP DIAGNOSTIC ON THE VAULT...")

# --- CONFIG ---
GRAD_CAM_LAYER = 'conv2d_transpose_3' # Target last upsampling layer for attention
if GRAD_CAM_LAYER not in [l.name for l in model.layers]:
    # Fallback to the last common decoder layer if specific name fails
    GRAD_CAM_LAYER = [l.name for l in model.layers if 'conv2d_transpose' in l.name][-1]

# --- 1. HARVEST METRICS ---
vault_data = []
all_true_flat = []
all_pred_flat = []
object_sizes = []
object_ious = []

print(f"   -> Analyzing {len(vault_img)} test images...")

for i, img_path in enumerate(vault_img):
    try:
        # Load
        img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

        # Inference
        pred_prob = model.predict(np.expand_dims(img, 0), verbose=0)[0][0]
        pred_mask = (pred_prob > 0.5).astype(np.float32)

        # Pixel Stats
        intersection = np.sum(true_mask * pred_mask)
        union = np.sum(true_mask) + np.sum(pred_mask) - intersection
        iou = intersection / (union + 1e-6)

        # Store for Global Metrics (Subsample pixels to save RAM if needed)
        # Using simple flattening here for exact metrics
        all_true_flat.extend(true_mask.flatten())
        all_pred_flat.extend(pred_prob.flatten()) # Keep probs for PR curve

        # Object Analysis (Size vs IoU)
        t_labeled = measure.label(true_mask[:,:,0])
        for region in measure.regionprops(t_labeled):
            if region.area < 50: continue
            # Isolate this specific cell mask
            obj_mask = (t_labeled == region.label).astype(np.float32)
            # Intersection with prediction
            obj_int = np.sum(obj_mask * pred_mask[:,:,0])
            obj_union = np.sum(obj_mask) + np.sum(pred_mask[:,:,0]) - obj_int
            # Local IoU for this object
            obj_iou = obj_int / (np.sum(obj_mask) + np.sum(pred_mask[:,:,0] * obj_mask) + 1e-6) # Approximate relative to object

            object_sizes.append(region.area)
            object_ious.append(obj_iou)

        vault_data.append({
            'id': i,
            'img': img,
            'true': true_mask,
            'pred': pred_prob,
            'iou': iou,
            'has_osteoclast': np.sum(true_mask) > 0
        })

    except Exception as e: print(f"Error on {i}: {e}")

# --- 2. GLOBAL PIXEL METRICS ---
print("\n" + "="*40)
print("📊 GLOBAL PIXEL-LEVEL REPORT")
print("="*40)
y_true = np.array(all_true_flat) > 0.5
y_scores = np.array(all_pred_flat)
y_pred_hard = y_scores > 0.5

g_tp = np.sum(y_true & y_pred_hard)
g_fp = np.sum((~y_true) & y_pred_hard)
g_fn = np.sum(y_true & (~y_pred_hard))

g_prec = g_tp / (g_tp + g_fp + 1e-6)
g_rec = g_tp / (g_tp + g_fn + 1e-6)
g_f1 = 2 * g_prec * g_rec / (g_prec + g_rec + 1e-6)
g_iou = g_tp / (g_tp + g_fp + g_fn + 1e-6)

print(f"Global Pixel F1:        {g_f1:.4f}")
print(f"Global Pixel IoU:       {g_iou:.4f}")
print(f"Global Pixel Precision: {g_prec:.4f}")
print(f"Global Pixel Recall:    {g_rec:.4f}")

# --- 3. PLOTS ---
fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# A. IoU Distribution
ious = [d['iou'] for d in vault_data]
sns.histplot(ious, bins=20, kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribution of IoU Scores (Test Set)')
axes[0].set_xlabel('IoU')

# B. Precision-Recall Curve
precision, recall, _ = precision_recall_curve(y_true, y_scores)
pr_auc = auc(recall, precision)
axes[1].plot(recall, precision, color='purple', label=f'AP={pr_auc:.2f}')
axes[1].set_title('Pixel Precision-Recall Curve')
axes[1].set_xlabel('Recall')
axes[1].set_ylabel('Precision')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# C. Size vs IoU
axes[2].scatter(object_sizes, object_ious, alpha=0.4, color='teal', s=10)
axes[2].set_title('Cell Size vs. Detection Quality')
axes[2].set_xlabel('Cell Area (Pixels)')
axes[2].set_ylabel('Object Overlap')
axes[2].set_xscale('log') # Log scale for area usually looks better
plt.show()

# --- 4. INTERPRETABILITY GRID (GRAD-CAM & UNCERTAINTY) ---
# Filter only images with actual cells
valid_data = [d for d in vault_data if d['has_osteoclast']]
valid_data.sort(key=lambda x: x['iou'])

top_5 = valid_data[-5:][::-1]
bot_5 = valid_data[:5]
display_set = top_5 + bot_5

def make_gradcam(img_tensor, model, layer_name):
    # Grad-CAM for the 'final' output class 0
    grad_model = Model([model.inputs], [model.get_layer(layer_name).output, model.output[0]])
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_tensor)
        loss = predictions[:, :, :, 0] # Target class 0

    output = conv_outputs[0]
    grads = tape.gradient(loss, conv_outputs)[0]

    weights = tf.reduce_mean(grads, axis=(0, 1))
    cam = tf.reduce_sum(tf.multiply(weights, output), axis=-1)

    cam = tf.maximum(cam, 0) # ReLU
    cam = cam / (tf.reduce_max(cam) + 1e-6) # Normalize
    cam = cam.numpy()
    cam = cv2.resize(cam, (512, 512))
    return cam

print("\n" + "="*60)
print(f"🧠 INTERPRETABILITY GRID (Top 5 vs Bottom 5 Performers)")
print(f"   -> Top Row: Best IoU | Bottom Row: Worst IoU")
print(f"   -> Saliency: Where the model is 'looking'")
print(f"   -> Uncertainty: Where the model is 'confused' (Entropy)")
print("="*60)

fig, axes = plt.subplots(10, 5, figsize=(20, 40))
cols = ["Input Image", "Ground Truth", "Prediction", "Saliency (Grad-CAM)", "Uncertainty (Entropy)"]

for ax, col in zip(axes[0], cols): ax.set_title(col, fontsize=14)

for i, data in enumerate(display_set):
    row_label = "TOP 5 (Best)" if i < 5 else "BOT 5 (Worst)"

    # 1. Image
    display_img = np.clip(data['img'] * IMAGENET_STD + IMAGENET_MEAN, 0, 1)
    axes[i, 0].imshow(display_img)
    axes[i, 0].set_ylabel(f"{row_label}\nIoU: {data['iou']:.2f}", fontsize=12)

    # 2. Truth
    axes[i, 1].imshow(data['true'][:,:,0], cmap='gray')

    # 3. Pred
    axes[i, 2].imshow(data['pred'][:,:,0], cmap='viridis')

    # 4. Saliency (Grad-CAM)
    try:
        input_tensor = np.expand_dims(data['img'], 0)
        heatmap = make_gradcam(input_tensor, model, GRAD_CAM_LAYER)
        axes[i, 3].imshow(display_img)
        axes[i, 3].imshow(heatmap, cmap='jet', alpha=0.5) # Overlay
    except: axes[i, 3].text(0.5, 0.5, "Layer Error", ha='center')

    # 5. Uncertainty (Entropy)
    # H = - (p*log(p) + (1-p)*log(1-p))
    p = np.clip(data['pred'][:,:,0], 1e-6, 1-1e-6)
    entropy = - (p * np.log(p) + (1-p) * np.log(1-p))
    axes[i, 4].imshow(entropy, cmap='magma')

    for ax in axes[i]: ax.set_xticks([]); ax.set_yticks([])

plt.tight_layout()
plt.show()

from tensorflow.keras.utils import plot_model

# This saves the image to your files and displays it right here in the notebook
plot_model(model, to_file='model_architecture.png', show_shapes=True, show_layer_names=True, dpi=96)