# -*- coding: utf-8 -*-
"""CHANA UNet with Domains

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uqWwhgUklGiXAHKrcDo6e59fWo7qEHyR

## CHANA TransUNet

A 3 phase domain adaptation implementation on a TransUNet architecture including 1. diffusionn based synthetic images 2. copy paste augmentation and 3. real data that is expert labelled. Total dataset size should be around 6.5k images.
"""

# CELL 1: ENVIRONMENT & IMPORTS
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations keras-unet-collection
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1" # Forces Keras 2 naming logic
os.environ["SM_FRAMEWORK"] = "tf.keras" # Force float32 for stability
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, Model, Input
from tensorflow.keras import mixed_precision
import segmentation_models as sm
import seaborn as sns
import pandas as pd
from skimage import io, measure, morphology
from scipy import ndimage
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve, average_precision_score
import gc

# Mount Drive
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- GLOBAL STABILITY SETTINGS ---
tf.config.experimental.enable_tensor_float_32_execution(True)
mixed_precision.set_global_policy('float32')
print(f"✅ TensorFlow {tf.__version__} Ready. Global Policy: Float32")

# CELL 2: CONFIGURATION & CURRICULUM (Full Domain Adaptation)
PROJECT_BASE_PATH = '/content/drive/MyDrive/CHANA_files'

# --- PATHS ---
# 1. Real Data (Gold Standard)
PREPROCESSED_IMAGES_DIR = os.path.join(PROJECT_BASE_PATH, 'preprocessed_rgb')
GROUND_TRUTH_MASKS_DIR = os.path.join(PROJECT_BASE_PATH, 'mask_images_512')

# 2. Synthetic Data Sources
DIFFUSION_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_training_data_v2_ancestral')
COPYPASTE_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_experiment/generated_images')
PSEUDO_DIR = os.path.join(PROJECT_BASE_PATH, 'pseudo_train_data', 'images')

# --- 📅 THE CURRICULUM SCHEDULE (Domain Adaptation) ---
CURRICULUM_PLAN = [
    {
        "stage": 1,
        "name": "Phase 1: Diffusion Pretraining",
        "description": "Learning Shapes from Synthetic Diffusion Data",
        "data_dir": DIFFUSION_DIR,
        "data_type": "diffusion",
        "epochs": 40,
        "init_lr": 1e-4,
        "loss_strategy": "robust",
        "save_path": os.path.join(PROJECT_BASE_PATH, 'Unet_DenseNet_Phase1_Diffusion.weights.h5')
    },
    {
        "stage": 2,
        "name": "Phase 2: Copy-Paste Bridging",
        "description": "Learning Texture/Boundaries from Copy-Paste Data",
        "data_dir": COPYPASTE_DIR,
        "data_type": "copypaste",
        "epochs": 80,
        "init_lr": 5e-5,
        "loss_strategy": "robust",
        "save_path": os.path.join(PROJECT_BASE_PATH, 'Unet_DenseNet_Phase2_CopyPaste.weights.h5')
    },
    {
        "stage": 2.5,
        "name": "Phase 2.5: Noisy Student (Pseudo-Labels)",
        "description": "Semi-Supervised Learning on Unlabeled Data",
        "data_dir": PSEUDO_DIR,
        "data_type": "pseudo",
        "epochs": 50,
        "init_lr": 2e-5,
        "loss_strategy": "soft", # Soft loss for noisy labels
        "save_path": os.path.join(PROJECT_BASE_PATH, 'Unet_DenseNet_Phase2.5_Pseudo.weights.h5')
    },
    {
        "stage": 3,
        "name": "Phase 3: Real Fine-Tuning",
        "description": "Final Polish on Real Expert Data",
        "data_dir": PREPROCESSED_IMAGES_DIR,
        "data_type": "real",
        "epochs": 200, # Long fine-tuning
        "init_lr": 1e-5, # Low LR for fine-tuning
        "loss_strategy": "robust",
        "save_path": os.path.join(PROJECT_BASE_PATH, 'Unet_DenseNet_withDomain.weights.h5')
    }
]

# Config
IMG_HEIGHT, IMG_WIDTH = 512, 512
IMG_CHANNELS = 3
NUM_CLASSES = 1
BATCH_SIZE = 16

print("🚀 CONFIGURATION READY: Full Domain Adaptation Pipeline")

# CELL 3: DATA LOADING UTILITIES (Standard / Single Output)
import albumentations as A

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def preprocess_input_v7(img):
    img = img.astype(np.float32) / 255.0
    img = (img - IMAGENET_MEAN) / IMAGENET_STD
    return img

aug_pipeline = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=20, p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.CoarseDropout(max_holes=6, max_height=24, max_width=24, p=0.3),
])

def augment_data(img, mask):
    aug = aug_pipeline(image=img, mask=mask)
    return aug['image'], aug['mask']

def load_and_process(img_path, mask_path):
    path_str = img_path.decode('utf-8')
    try:
        img = cv2.imread(path_str, cv2.IMREAD_COLOR)
        if img is None: # Fallback for TIF/Special formats
            img = io.imread(path_str)
            if img.ndim == 2: img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
            elif img.shape[2] == 4: img = img[:,:,:3]
    except:
        return np.zeros((512,512,3), dtype=np.float32), np.zeros((512,512,1), dtype=np.float32)

    if img is not None:
        if path_str.lower().endswith(('.png', '.jpg')):
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img, (512, 512), interpolation=cv2.INTER_AREA)
    img = preprocess_input_v7(img)

    m_path_str = mask_path.decode('utf-8')
    if m_path_str.endswith('.tif'): mask = io.imread(m_path_str)
    else: mask = cv2.imread(m_path_str, cv2.IMREAD_GRAYSCALE)
    if mask is None: mask = io.imread(m_path_str)

    if mask.shape[:2] != (512, 512):
        mask = cv2.resize(mask, (512, 512), interpolation=cv2.INTER_NEAREST)

    mask = (mask > 0).astype(np.float32)
    if mask.ndim == 2: mask = np.expand_dims(mask, axis=-1)

    return img, mask

def create_tf_dataset(images, masks, training=True):
    ds = tf.data.Dataset.from_tensor_slices((images, masks))
    ds = ds.shuffle(len(images)) if training else ds
    ds = ds.repeat()

    ds = ds.map(lambda i, m: tf.numpy_function(load_and_process, [i, m], [tf.float32, tf.float32]),
                num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.map(lambda i, m: tf.numpy_function(augment_data, [i, m], [tf.float32, tf.float32]),
                    num_parallel_calls=tf.data.AUTOTUNE)

    # --- STANDARD FORMATTING (Single Output) ---
    def format_output(i, m):
        i = tf.ensure_shape(i, [512, 512, 3])
        m = tf.ensure_shape(m, [512, 512, 1])
        return i, m # Only one mask!

    ds = ds.map(format_output, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

print("✅ Data Loader Updated: Standard Mode (Single Output)")

# CELL 4: ARCHITECTURE (Native Standard U-Net / DenseNet121 / Robust)
# ==============================================================================
# FIXED: Automatically detects if layers use '/' (Legacy) or '_' (Keras 3).
# PREVENTS: "No such layer" and "Invalid character" errors.
# ==============================================================================

import tensorflow as tf
from tensorflow.keras import layers, Model, Input
from tensorflow.keras.applications import DenseNet121

def build_custom_unet(input_shape, num_classes):
    print(f"🏗️ Building Native Standard U-Net (DenseNet121)...")

    # 1. INPUT
    inputs = Input(shape=input_shape, name='input_layer')

    # 2. BACKBONE (Encoder)
    encoder = DenseNet121(include_top=False, weights='imagenet', input_tensor=inputs)
    encoder.trainable = True

    # --- HELPER: ROBUST LAYER EXTRACTOR ---
    def get_layer_output(model, name_options):
        """Tries to find a layer matching one of the names in the list."""
        for name in name_options:
            try:
                return model.get_layer(name).output
            except ValueError:
                continue
        # If we get here, none matched. Print available layers for debugging.
        print(f"❌ Critical Error: Could not find layer. Tried: {name_options}")
        raise ValueError(f"Could not find any valid layer name in {name_options}")

    # 3. SKIP CONNECTIONS (Checking both Slash and Underscore names)
    # --------------------------------------------------------------------------
    # Level 1: 256x256
    s1 = get_layer_output(encoder, ['conv1/relu', 'conv1_relu'])

    # Level 2: 128x128
    s2 = get_layer_output(encoder, ['conv2_block6_concat', 'conv2/block6/concat'])

    # Level 3: 64x64
    s3 = get_layer_output(encoder, ['conv3_block12_concat', 'conv3/block12/concat'])

    # Level 4: 32x32
    s4 = get_layer_output(encoder, ['conv4_block24_concat', 'conv4/block24/concat'])

    # Bridge: 16x16
    bridge = get_layer_output(encoder, ['conv5_block16_concat', 'conv5/block16/concat'])
    # --------------------------------------------------------------------------

    # 4. DECODER
    def decoder_block(input_tensor, skip_tensor, filters):
        x = layers.Conv2DTranspose(filters, (2, 2), strides=(2, 2), padding='same')(input_tensor)
        x = layers.Concatenate()([x, skip_tensor])
        x = layers.Conv2D(filters, (3, 3), padding='same', activation='relu')(x)
        x = layers.Conv2D(filters, (3, 3), padding='same', activation='relu')(x)
        return x

    d1 = decoder_block(bridge, s4, 512)
    d2 = decoder_block(d1, s3, 256)
    d3 = decoder_block(d2, s2, 128)
    d4 = decoder_block(d3, s1, 64)

    # Final Upsample
    d5 = layers.Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(d4)
    d5 = layers.Conv2D(32, (3, 3), padding='same', activation='relu')(d5)

    # 5. OUTPUT HEAD (Standard Single Output)
    outputs = layers.Conv2D(num_classes, (1, 1), activation='sigmoid', name='final_output', dtype='float32')(d5)

    final_model = Model(inputs=inputs, outputs=outputs, name="Standard_DenseNet_UNet")

    print(f"✅ Architecture Ready: Standard U-Net (DenseNet121)")
    print(f"   -> Outputs: 1 (Standard)")

    return final_model

print("✅ Cell 4 Updated: Robust Layer Naming Implemented.")

# CELL 5: DYNAMIC LOSS STRATEGIES
import tensorflow.keras.backend as K

# Strategy 1: "Robust" (Focal Tversky) - For Trusted Labels
def focal_tversky_loss(y_true, y_pred, alpha=0.3, beta=0.7, gamma=1.5):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    tp = K.sum(y_true_f * y_pred_f)
    fn = K.sum(y_true_f * (1 - y_pred_f))
    fp = K.sum((1 - y_true_f) * y_pred_f)
    tversky = (tp + 1e-6) / (tp + alpha * fn + beta * fp + 1e-6)
    return K.pow((1 - tversky), gamma)

# Strategy 2: "Soft" (BCE + Label Smoothing) - For Noisy Labels/Arrogant Models
def soft_bce_loss(y_true, y_pred):
    # Standard BCE with label smoothing (0.1 means target becomes 0.95/0.05)
    return tf.keras.losses.binary_crossentropy(y_true, y_pred, label_smoothing=0.1)

def dice_loss_fn(y_true, y_pred):
    smooth = 1e-6
    intersection = K.sum(y_true * y_pred)
    return 1 - (2. * intersection + smooth) / (K.sum(y_true) + K.sum(y_pred) + smooth)

common_metrics = [sm.metrics.iou_score, sm.metrics.f1_score]

# CELL 6: "THE VAULT" - STRICT DATA SPLITTING
print("🚜 Harvesting Real Data...")
all_real_img, all_real_mask = [], []

# 1. Harvest
for f in os.listdir(PREPROCESSED_IMAGES_DIR):
    if f.lower().endswith(('.png', '.tif', '.jpg')):
        base = os.path.splitext(f)[0]
        # Robust mask finding
        for ext in ['_mask.tif', '_mask.png', '.tif', '.png']:
            p = os.path.join(GROUND_TRUTH_MASKS_DIR, base + ext)
            if os.path.exists(p):
                all_real_img.append(os.path.join(PREPROCESSED_IMAGES_DIR, f))
                all_real_mask.append(p)
                break

# 2. Split 1: Isolate The Vault (15%)
remaining_img, vault_img, remaining_mask, vault_mask = train_test_split(
    all_real_img, all_real_mask, test_size=0.15, random_state=999 # Fixed seed
)

# 3. Split 2: Train vs Val (Validation 15% of original, approx 17% of remaining)
train_real_img, val_real_img, train_real_mask, val_real_mask = train_test_split(
    remaining_img, remaining_mask, test_size=0.176, random_state=42
)

print(f"🔒 THE VAULT (Test Set) Sealed: {len(vault_img)} images.")
print(f"📖 Validation Set Ready:       {len(val_real_img)} images.")
print(f"🏋️ Training Set Ready:         {len(train_real_img)} images.")

# Create the Validation Dataset ONCE for consistency
val_dataset = create_tf_dataset(val_real_img, val_real_mask, training=False)
STEPS_PER_EPOCH_VAL = len(val_real_img) // BATCH_SIZE

# Save Vault list
with open('VAULT_FILES.txt', 'w') as f:
    for item in vault_img: f.write(f"{item}\n")

# CELL 7: OBJECT-LEVEL METRICS CALLBACK (TRAINING MONITOR)
from tensorflow.keras.callbacks import Callback

class ObjectMetricsCallback(Callback):
    def __init__(self, val_images, val_masks, freq=1):
        super().__init__()
        self.val_images = val_images[:100] # Check first 100 for speed
        self.val_masks = val_masks[:100]
        self.freq = freq

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.freq != 0: return

        total_tp, total_fp, total_fn = 0, 0, 0
        min_area = 50

        # Run inference on subset
        for i, img_p in enumerate(self.val_images):
            try:
                # Load (Re-using helper)
                img, true_mask = load_and_process(img_p.encode('utf-8'), self.val_masks[i].encode('utf-8'))

                # Predict
                pred_prob = self.model.predict(np.expand_dims(img, 0), verbose=0)[0][0]

                # Threshold & Process
                p_mask = np.squeeze((pred_prob > 0.5).astype(np.uint8))
                p_mask = ndimage.binary_fill_holes(p_mask).astype(np.uint8)
                t_mask = np.squeeze((true_mask > 0.5).astype(np.uint8))

                # Count
                p_cents = [r.centroid for r in measure.regionprops(measure.label(p_mask)) if r.area > min_area]
                t_cents = [r.centroid for r in measure.regionprops(measure.label(t_mask)) if r.area > min_area]

                # Match
                matches = 0
                if t_cents and p_cents:
                    dists = cdist(t_cents, p_cents)
                    rows, cols = linear_sum_assignment(dists)
                    for r, c in zip(rows, cols):
                        if dists[r, c] < 25: matches += 1

                total_tp += matches
                total_fp += len(p_cents) - matches
                total_fn += len(t_cents) - matches
            except: pass

        # Calc Metrics
        prec = total_tp / (total_tp + total_fp + 1e-6)
        rec = total_tp / (total_tp + total_fn + 1e-6)
        f1 = 2 * prec * rec / (prec + rec + 1e-6)

        print(f"\n   🎯 [Epoch {epoch+1}] Object Metrics -> F1: {f1:.4f} | Prec: {prec:.4f} | Rec: {rec:.4f}")
        logs['val_object_f1'] = f1

# CELL 8: THE MASTER TRAINING LOOP (Domain Adaptation Enabled)
from tensorflow.keras.optimizers import AdamW

# 1. Initialize Model
tf.keras.backend.clear_session()
gc.collect()
# This uses your existing Cell 4 (Native DenseNet)
model = build_custom_unet(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), num_classes=NUM_CLASSES)
print("🏗️ Model Initialized.")

# 2. Iterate Curriculum
for plan in CURRICULUM_PLAN:
    print(f"\n" + "="*60)
    print(f"🎬 STARTING {plan['name']}")
    print("="*60)

    # A. DYNAMIC DATA HARVESTING
    current_train_img, current_train_mask = [], []

    if plan['data_type'] == 'diffusion':
        # Look for _image.png / _mask.png pairs
        for f in os.listdir(plan['data_dir']):
            if f.endswith('_image.png'):
                mask_p = os.path.join(plan['data_dir'], f.replace('_image.png', '_mask.png'))
                if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'copypaste':
        # Images in 'generated_images', Masks in 'generated_masks'
        base_dir = os.path.dirname(plan['data_dir'])
        cp_mask_dir = os.path.join(base_dir, 'generated_masks')
        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg')):
                # Check standard naming
                possible = [f, f.replace('.png', '_mask.png'), f.replace('.jpg', '_mask.png')]
                for m_name in possible:
                    mask_p = os.path.join(cp_mask_dir, m_name)
                    if os.path.exists(mask_p):
                        current_train_img.append(os.path.join(plan['data_dir'], f))
                        current_train_mask.append(mask_p)
                        break

    elif plan['data_type'] == 'pseudo':
        # Images in 'images', Masks in 'masks'
        base_dir = os.path.dirname(plan['data_dir'])
        pseudo_mask_dir = os.path.join(base_dir, 'masks')
        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg', '.tif')):
                 mask_p = os.path.join(pseudo_mask_dir, f) # Try exact match
                 if not os.path.exists(mask_p):
                     mask_p = os.path.join(pseudo_mask_dir, os.path.splitext(f)[0] + "_mask.png")
                 if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'real':
        current_train_img = train_real_img
        current_train_mask = train_real_mask

    print(f"   -> Found {len(current_train_img)} training pairs.")

    if len(current_train_img) == 0:
        print(f"⚠️ WARNING: No data found for {plan['name']}. Skipping stage.")
        continue

    # B. DATASET CREATION
    train_ds = create_tf_dataset(current_train_img, current_train_mask, training=True)
    # Validation is always REAL data
    val_dataset_standard = create_tf_dataset(val_real_img, val_real_mask, training=False)

    steps_per_epoch = len(current_train_img) // BATCH_SIZE

    # C. OPTIMIZER & LOSS
    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=plan['init_lr'],
        decay_steps=plan['epochs'] * steps_per_epoch,
        alpha=0.01
    )
    optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

    if plan['loss_strategy'] == 'soft':
        loss_fn = soft_bce_loss
    else:
        loss_fn = focal_tversky_loss

    model.compile(
        optimizer=optimizer,
        loss=loss_fn,
        metrics=common_metrics
    )

    # D. CALLBACKS
    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            plan['save_path'], monitor='val_loss', mode='min',
            save_best_only=True, save_weights_only=True, verbose=1
        ),
        ObjectMetricsCallback(val_real_img, val_real_mask, freq=5),

        # Patience 35
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss', mode='min', patience=35, restore_best_weights=True, verbose=1
        ),

        tf.keras.callbacks.CSVLogger(os.path.join(PROJECT_BASE_PATH, f"log_Domain_{plan['stage']}.csv"))
    ]

    # E. TRAIN
    model.fit(
        train_ds,
        steps_per_epoch=steps_per_epoch,
        epochs=plan['epochs'],
        validation_data=val_dataset_standard,
        validation_steps=STEPS_PER_EPOCH_VAL,
        callbacks=callbacks
    )

    print(f"✅ {plan['name']} Complete. Loading best weights...")
    model.load_weights(plan['save_path'])

print("\n🏆 DOMAIN ADAPTATION TRAINING COMPLETE.")

# CELL 9: "THE VAULT" PIXEL EVALUATION (Fixed)
import pandas as pd

print("⚖️ UNLOCKING THE VAULT: Final Evaluation...")

# 1. SETUP PATHS
# If you ran the 'Domain Adaptation' schedule, use this name:
model_filename = 'Unet_DenseNet_withDomain.weights.h5'

# If you ran the 'Without Domain' schedule, uncomment this line instead:
# model_filename = 'Unet_DenseNet_withoutDomain.weights.h5'

final_model_path = os.path.join(PROJECT_BASE_PATH, model_filename)

# 2. LOAD WEIGHTS
print(f"   -> Loading weights from: {model_filename}")
try:
    model.load_weights(final_model_path)
    print("✅ Weights loaded successfully.")
except FileNotFoundError:
    print(f"❌ ERROR: Could not find file {final_model_path}")
    print("   Did you finish training Cell 8?")

# 3. RUN INFERENCE
vault_metrics = []
print(f"   -> Processing {len(vault_img)} unseen test images...")

for i, img_path in enumerate(vault_img):
    try:
        # FIXED: .encode('utf-8') added because load_and_process expects bytes
        img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

        # Predict
        preds = model.predict(np.expand_dims(img, 0), verbose=0)

        # FIXED: Handle Single Output vs List (Robust)
        if isinstance(preds, list):
            raw_pred = preds[-1]
        else:
            raw_pred = preds

        # FIXED: Squeeze to 2D for IoU Calculation
        pred_prob = np.squeeze(raw_pred)
        if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0]

        # Prepare Masks
        p_mask_bin = (pred_prob > 0.5).astype(np.float32)

        t_mask = np.squeeze(true_mask)
        if t_mask.ndim == 3: t_mask = t_mask[..., 0]
        t_mask_bin = (t_mask > 0.5).astype(np.float32)

        # Calculate IoU
        intersection = np.sum(t_mask_bin * p_mask_bin)
        union = np.sum(t_mask_bin) + np.sum(p_mask_bin) - intersection

        if np.sum(t_mask_bin) == 0 and np.sum(p_mask_bin) == 0:
            iou = 1.0 # Perfect rejection (Empty mask matched empty prediction)
        else:
            iou = intersection / (union + 1e-6)

        vault_metrics.append({'path': img_path, 'iou': iou})

    except Exception as e:
        if i < 5: print(f"Error on {i}: {e}")

# 4. REPORT
if vault_metrics:
    df_vault = pd.DataFrame(vault_metrics)
    print("\n" + "="*40)
    print(f"🏛️ FINAL TEST SET (VAULT) REPORT")
    print(f"   Model: {model_filename}")
    print("="*40)
    print(f"Mean IoU: {df_vault['iou'].mean():.4f}")
    print("="*40)
else:
    print("❌ No metrics calculated. Check paths/errors.")

# CELL 10: HUNGARIAN MATCHING & VISUALIZATION (Fixed for Standard U-Net)
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

print("\n--- Object-Level Evaluation (Vault) ---")

# --- CONFIG ---
MIN_AREA = 50
MAX_DISTANCE = 25
SAMPLE_LIMIT = 50

# --- DATA TARGETING ---
target_img_list = vault_img
target_mask_list = vault_mask

# --- HELPER: Plotting ---
def plot_object_detection(img, t_cents, p_cents, matches):
    display_img = np.clip(img * IMAGENET_STD + IMAGENET_MEAN, 0, 1)

    plt.figure(figsize=(8, 8))
    plt.imshow(display_img)

    if t_cents:
        t_arr = np.array(t_cents)
        plt.plot(t_arr[:, 1], t_arr[:, 0], 'bo', markersize=10, fillstyle='none', markeredgewidth=2, label='Truth')
    if p_cents:
        p_arr = np.array(p_cents)
        plt.plot(p_arr[:, 1], p_arr[:, 0], 'rx', markersize=10, markeredgewidth=2, label='Pred')

    for t_idx, p_idx in matches:
        tr, tc = t_cents[t_idx]
        pr, pc = p_cents[p_idx]
        plt.plot([tc, pc], [tr, pr], 'g-', linewidth=2, alpha=0.7)

    plt.legend(loc='upper right')
    plt.axis('off')
    plt.show()

# --- EXECUTION ---
total_tp, total_fp, total_fn = 0, 0, 0

print(f"   -> Analyzing first {SAMPLE_LIMIT} images for object detection...")

for i, img_path in enumerate(target_img_list[:SAMPLE_LIMIT]):
    try:
        # FIXED: Added .encode('utf-8') to prevent AttributeErrors
        img, true_mask = load_and_process(img_path.encode('utf-8'), target_mask_list[i].encode('utf-8'))

        # Predict
        preds = model.predict(np.expand_dims(img, 0), verbose=0)

        # FIXED: Robust Single-Output Handling
        if isinstance(preds, list):
            raw_pred = preds[-1]
        else:
            raw_pred = preds

        # FIXED: Immediate Squeeze to 2D
        pred_prob = np.squeeze(raw_pred)
        if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0] # Safety

        # Threshold & Fill Holes
        p_mask_2d = (pred_prob > 0.5).astype(np.uint8)
        p_mask_2d = ndimage.binary_fill_holes(p_mask_2d).astype(np.uint8)

        # Process Truth (Force 2D)
        t_mask_2d = np.squeeze(true_mask)
        if t_mask_2d.ndim == 3: t_mask_2d = t_mask_2d[..., 0]
        t_mask_2d = (t_mask_2d > 0.5).astype(np.uint8)

        # Get Centroids
        p_props = measure.regionprops(measure.label(p_mask_2d))
        p_cents = [r.centroid for r in p_props if MIN_AREA < r.area < 10000]

        t_props = measure.regionprops(measure.label(t_mask_2d))
        t_cents = [r.centroid for r in t_props if MIN_AREA < r.area < 10000]

        # Match (Hungarian Algorithm)
        matches = []
        tp_curr = 0

        if len(t_cents) > 0 and len(p_cents) > 0:
            t_arr = np.array(t_cents)
            p_arr = np.array(p_cents)
            dists = cdist(t_arr, p_arr)
            rows, cols = linear_sum_assignment(dists)

            for row, col in zip(rows, cols):
                if dists[row, col] < MAX_DISTANCE:
                    matches.append((row, col))
                    tp_curr += 1

        fp_curr = len(p_cents) - tp_curr
        fn_curr = len(t_cents) - tp_curr

        total_tp += tp_curr
        total_fp += fp_curr
        total_fn += fn_curr

        # Visualize first 3
        if i < 3 and (t_cents or p_cents):
            plot_object_detection(img, t_cents, p_cents, matches)

    except Exception as e:
        if i < 5: print(f"Skip {i}: {e}")

# --- METRICS ---
precision = total_tp / (total_tp + total_fp + 1e-6)
recall = total_tp / (total_tp + total_fn + 1e-6)
f1 = 2 * precision * recall / (precision + recall + 1e-6)

print("\n" + "="*40)
print(f"🎯 OBJECT-LEVEL METRICS (VAULT)")
print("="*40)
print(f"Global F1 Score: {f1:.4f}")
print(f"Global Precision: {precision:.4f}")
print(f"Global Recall:    {recall:.4f}")
print("="*40)

# CELL 11: SIZE BIN ANALYSIS (Fixed: Encoding & Shape)
import pandas as pd
import seaborn as sns
from skimage import measure

print("--- Deep Diagnostics by Object Size (Vault) ---")

# --- CONFIG ---
# 0-500px: Small | 500-1500px: Medium | 1500px+: Large
SIZE_BINS = [0, 500, 1500, 10000]
BIN_LABELS = ['Small', 'Medium', 'Large']
object_data = []

if vault_img:
    # Limit to 100 images for speed, or remove [:100] for full set
    print(f"   -> Analyzing sizes for {min(100, len(vault_img))} images...")

    for i, img_path in enumerate(vault_img[:100]):
        try:
            # FIXED: Added .encode('utf-8') for string paths
            img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

            # Predict
            preds = model.predict(np.expand_dims(img, 0), verbose=0)

            # FIXED: Handle Single Output vs List
            if isinstance(preds, list):
                raw_pred = preds[-1]
            else:
                raw_pred = preds

            # FIXED: Force 2D Shape
            pred_prob = np.squeeze(raw_pred)
            if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0]

            # Process Masks
            p_mask = (pred_prob > 0.5).astype(np.uint8)

            t_mask = np.squeeze(true_mask)
            if t_mask.ndim == 3: t_mask = t_mask[..., 0]
            t_mask = (t_mask > 0.5).astype(np.uint8)

            # Analyze Objects
            true_labels = measure.label(t_mask, connectivity=2)
            for t_region in measure.regionprops(true_labels):
                if t_region.area < 50: continue # Ignore noise

                t_mask_iso = (true_labels == t_region.label)
                intersection = np.logical_and(t_mask_iso, p_mask).sum()
                coverage = intersection / t_region.area

                object_data.append({
                    'Area': t_region.area,
                    'Detected': coverage > 0.5, # Considered detected if >50% overlap
                    'IoU': coverage
                })
        except Exception as e:
            pass # Skip errors to keep loop running

    if object_data:
        obj_df = pd.DataFrame(object_data)
        obj_df['Size_Bin'] = pd.cut(obj_df['Area'], bins=SIZE_BINS, labels=BIN_LABELS)

        print("\nDetection Rate by Size:")
        print(obj_df.groupby('Size_Bin')['Detected'].mean())

        plt.figure(figsize=(8, 5))
        sns.barplot(data=obj_df, x='Size_Bin', y='Detected', palette='viridis')
        plt.title("Probability of Detecting a Cell vs. Cell Size")
        plt.ylabel("Detection Probability")
        plt.ylim(0, 1.0)
        plt.grid(axis='y', alpha=0.3)
        plt.show()
    else:
        print("No objects found to analyze.")
else:
    print("Vault is empty.")

# CELL 12: DEEP DIVE DIAGNOSTIC (Fixed: Encoding & Shape)
import matplotlib.cm as cm
from sklearn.metrics import auc, precision_recall_curve
from tensorflow.keras.layers import Conv2D, Conv2DTranspose

print("🔬 STARTING DEEP DIAGNOSTIC...")

# 1. ROBUST LAYER SEARCH
target_layer = None
potential_layers = []

for layer in model.layers:
    if isinstance(layer, Conv2DTranspose):
        potential_layers.append(layer.name)

if len(potential_layers) >= 1:
    GRAD_CAM_LAYER = potential_layers[-1]
else:
    # Fallback for Native Models where names might be generic
    GRAD_CAM_LAYER = model.layers[-2].name

print(f"   -> Using Layer for Saliency: {GRAD_CAM_LAYER}")

# 2. METRIC HARVESTING
vault_data = []
all_true_flat = []
all_pred_flat = []
object_sizes = []
object_ious = []

print(f"   -> Processing {len(vault_img)} test images...")

for i, img_path in enumerate(vault_img):
    try:
        # FIXED: Encoding inputs for load_and_process
        img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

        # Predict
        preds = model.predict(np.expand_dims(img, 0), verbose=0)

        # FIXED: Robust Output Handling
        if isinstance(preds, list):
            raw_pred = preds[-1]
        else:
            raw_pred = preds

        # FIXED: Squeeze to 2D
        pred_prob = np.squeeze(raw_pred)
        if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0]

        true_mask_2d = np.squeeze(true_mask)
        if true_mask_2d.ndim == 3: true_mask_2d = true_mask_2d[..., 0]

        # Threshold
        pred_mask_2d = (pred_prob > 0.5).astype(np.float32)
        true_mask_2d = (true_mask_2d > 0.5).astype(np.float32)

        # Pixel Stats
        intersection = np.sum(true_mask_2d * pred_mask_2d)
        union = np.sum(true_mask_2d) + np.sum(pred_mask_2d) - intersection

        if np.sum(true_mask_2d) == 0 and np.sum(pred_mask_2d) == 0:
            iou = 1.0
        else:
            iou = intersection / (union + 1e-6)

        # Store Data
        all_true_flat.extend(true_mask_2d.flatten())
        all_pred_flat.extend(pred_prob.flatten())

        # Object Analysis
        t_labeled = measure.label(true_mask_2d)
        for region in measure.regionprops(t_labeled):
            if region.area < 50: continue
            obj_mask = (t_labeled == region.label).astype(np.float32)
            obj_int = np.sum(obj_mask * pred_mask_2d)
            obj_union = np.sum(obj_mask) + np.sum(pred_mask_2d * obj_mask) - obj_int
            obj_iou = obj_int / (obj_union + 1e-6)
            object_sizes.append(region.area)
            object_ious.append(obj_iou)

        vault_data.append({
            'id': i, 'path': img_path, 'img': img,
            'true': true_mask_2d, 'pred': pred_prob, 'iou': iou
        })

    except Exception as e:
        if i < 5: print(f"Error on {i}: {e}")

# --- 3. GLOBAL PLOTS ---
print("\n" + "="*40)
print("📊 GLOBAL REPORT & DISPERSION GRAPHS")
print("="*40)

if len(vault_data) == 0:
    print("❌ NO DATA COLLECTED.")
else:
    # A. Global Pixel Metrics
    y_true = np.array(all_true_flat) > 0.5
    y_scores = np.array(all_pred_flat)
    y_pred_hard = y_scores > 0.5

    g_tp = np.sum(y_true & y_pred_hard)
    g_fp = np.sum((~y_true) & y_pred_hard)
    g_fn = np.sum(y_true & (~y_pred_hard))

    g_prec = g_tp / (g_tp + g_fp + 1e-6)
    g_rec = g_tp / (g_tp + g_fn + 1e-6)
    g_f1 = 2 * g_prec * g_rec / (g_prec + g_rec + 1e-6)
    g_iou = g_tp / (g_tp + g_fp + g_fn + 1e-6)

    print(f"Global Pixel F1:        {g_f1:.4f}")
    print(f"Global Pixel IoU:       {g_iou:.4f}")
    print(f"Global Pixel Precision: {g_prec:.4f}")
    print(f"Global Pixel Recall:    {g_rec:.4f}")

    # B. Plotting
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))

    # 1. IoU Histogram
    ious = [d['iou'] for d in vault_data]
    sns.histplot(ious, bins=20, kde=True, ax=axes[0], color='skyblue')
    axes[0].set_title('Distribution of IoU Scores')
    axes[0].set_xlabel('IoU')

    # 2. Precision-Recall Curve
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    pr_auc = auc(recall, precision)
    axes[1].plot(recall, precision, color='purple', label=f'AP={pr_auc:.2f}')
    axes[1].set_title('Pixel Precision-Recall Curve')
    axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')
    axes[1].legend()

    # 3. Size vs Quality
    if object_sizes:
        axes[2].scatter(object_sizes, object_ious, alpha=0.4, color='teal', s=10)
        axes[2].set_title('Cell Size vs. Detection Quality')
        axes[2].set_xlabel('Pixel Area'); axes[2].set_ylabel('Object IoU')
        axes[2].set_xscale('log')
    else:
        axes[2].text(0.5, 0.5, "No Objects Found", ha='center')

    plt.tight_layout()
    plt.show()

# --- 4. VISUALIZATION GRID ---
print("\n🧠 INTERPRETABILITY GRID")
def make_gradcam(img_tensor, model, layer_name):
    grad_model = Model(model.inputs, [model.get_layer(layer_name).output, model.output])
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_tensor)
        if isinstance(predictions, list): predictions = predictions[-1]
        loss = predictions[:, :, :, 0]
    grads = tape.gradient(loss, conv_outputs)
    if grads is None: return np.zeros((512,512))
    weights = tf.reduce_mean(grads[0], axis=(0, 1))
    cam = tf.reduce_sum(tf.multiply(weights, conv_outputs[0]), axis=-1)
    cam = tf.maximum(cam, 0)
    return cv2.resize(cam.numpy(), (512, 512))

valid_data = [d for d in vault_data if d['iou'] > 0.1]
valid_data.sort(key=lambda x: x['iou'])
display_set = valid_data[-3:][::-1] + valid_data[:3]

if display_set:
    fig, axes = plt.subplots(len(display_set), 4, figsize=(16, 4*len(display_set)))
    if len(display_set) == 1: axes = [axes]

    cols = ["Input", "Truth", "Pred", "Grad-CAM"]
    for ax, col in zip(axes[0], cols): ax.set_title(col, fontsize=12, fontweight='bold')

    for i, item in enumerate(display_set):
        display_img = np.clip(item['img'] * IMAGENET_STD + IMAGENET_MEAN, 0, 1)
        row_axes = axes[i] if len(display_set) > 1 else axes

        row_axes[0].imshow(display_img)
        row_axes[0].set_ylabel(f"IoU: {item['iou']:.2f}")
        row_axes[1].imshow(item['true'], cmap='gray')
        row_axes[2].imshow(item['pred'], cmap='viridis')

        try:
            heatmap = make_gradcam(np.expand_dims(item['img'], 0), model, GRAD_CAM_LAYER)
            row_axes[3].imshow(display_img)
            row_axes[3].imshow(heatmap, cmap='jet', alpha=0.5)
        except: row_axes[3].text(0.5, 0.5, "Error", ha='center')

        for ax in row_axes: ax.set_xticks([]); ax.set_yticks([])

    plt.tight_layout()
    plt.show()
else:
    print("Not enough valid predictions to generate grid.")

# CELL 12: DEEP DIVE DIAGNOSTIC (Fixed Input Encoding)
import matplotlib.cm as cm
from sklearn.metrics import auc, precision_recall_curve
from tensorflow.keras.layers import Conv2D, Conv2DTranspose

print("🔬 STARTING DEEP DIAGNOSTIC...")

# 1. ROBUST LAYER SEARCH
target_layer = None
potential_layers = []

for layer in model.layers:
    if isinstance(layer, Conv2DTranspose):
        potential_layers.append(layer.name)

if len(potential_layers) >= 1:
    GRAD_CAM_LAYER = potential_layers[-1]
else:
    GRAD_CAM_LAYER = model.layers[-2].name

print(f"   -> Using Layer for Saliency: {GRAD_CAM_LAYER}")

# 2. METRIC HARVESTING
vault_data = []
all_true_flat = []
all_pred_flat = []
object_sizes = []
object_ious = []

print(f"   -> Processing {len(vault_img)} test images...")

for i, img_path in enumerate(vault_img):
    try:
        # --- FIXED LINE BELOW ---
        # We must encode the string paths to bytes ('utf-8')
        # because Cell 3's load_and_process expects bytes.
        img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

        # Predict
        preds = model.predict(np.expand_dims(img, 0), verbose=0)

        if isinstance(preds, list):
            raw_pred = preds[-1]
        else:
            raw_pred = preds

        # Squeeze to 2D
        pred_prob = np.squeeze(raw_pred)
        true_mask_2d = np.squeeze(true_mask)

        # Safety check for dimensions
        if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0]
        if true_mask_2d.ndim == 3: true_mask_2d = true_mask_2d[..., 0]

        # Threshold
        pred_mask_2d = (pred_prob > 0.5).astype(np.float32)
        true_mask_2d = (true_mask_2d > 0.5).astype(np.float32)

        # Pixel Stats
        intersection = np.sum(true_mask_2d * pred_mask_2d)
        union = np.sum(true_mask_2d) + np.sum(pred_mask_2d) - intersection

        if np.sum(true_mask_2d) == 0 and np.sum(pred_mask_2d) == 0:
            iou = 1.0
        else:
            iou = intersection / (union + 1e-6)

        # Store
        all_true_flat.extend(true_mask_2d.flatten())
        all_pred_flat.extend(pred_prob.flatten())

        # Object Analysis
        t_labeled = measure.label(true_mask_2d)
        for region in measure.regionprops(t_labeled):
            if region.area < 50: continue
            obj_mask = (t_labeled == region.label).astype(np.float32)
            obj_int = np.sum(obj_mask * pred_mask_2d)
            obj_union = np.sum(obj_mask) + np.sum(pred_mask_2d * obj_mask) - obj_int
            obj_iou = obj_int / (obj_union + 1e-6)
            object_sizes.append(region.area)
            object_ious.append(obj_iou)

        vault_data.append({
            'id': i, 'path': img_path, 'img': img,
            'true': true_mask_2d, 'pred': pred_prob, 'iou': iou
        })

    except Exception as e:
        if i < 5: print(f"Error on {i}: {e}")

# --- 3. GLOBAL PLOTS ---
print("\n" + "="*40)
print("📊 GLOBAL REPORT & DISPERSION GRAPHS")
print("="*40)

if len(vault_data) == 0:
    print("❌ NO DATA COLLECTED.")
else:
    # A. Global Pixel Metrics
    y_true = np.array(all_true_flat) > 0.5
    y_scores = np.array(all_pred_flat)
    y_pred_hard = y_scores > 0.5

    g_tp = np.sum(y_true & y_pred_hard)
    g_fp = np.sum((~y_true) & y_pred_hard)
    g_fn = np.sum(y_true & (~y_pred_hard))

    g_prec = g_tp / (g_tp + g_fp + 1e-6)
    g_rec = g_tp / (g_tp + g_fn + 1e-6)
    g_f1 = 2 * g_prec * g_rec / (g_prec + g_rec + 1e-6)
    g_iou = g_tp / (g_tp + g_fp + g_fn + 1e-6)

    print(f"Global Pixel F1:        {g_f1:.4f}")
    print(f"Global Pixel IoU:       {g_iou:.4f}")
    print(f"Global Pixel Precision: {g_prec:.4f}")
    print(f"Global Pixel Recall:    {g_rec:.4f}")

    # B. Plotting
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))

    # 1. IoU Histogram
    ious = [d['iou'] for d in vault_data]
    sns.histplot(ious, bins=20, kde=True, ax=axes[0], color='skyblue')
    axes[0].set_title('Distribution of IoU Scores')
    axes[0].set_xlabel('IoU')

    # 2. Precision-Recall Curve
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    pr_auc = auc(recall, precision)
    axes[1].plot(recall, precision, color='purple', label=f'AP={pr_auc:.2f}')
    axes[1].set_title('Pixel Precision-Recall Curve')
    axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')
    axes[1].legend()

    # 3. Size vs Quality
    if object_sizes:
        axes[2].scatter(object_sizes, object_ious, alpha=0.4, color='teal', s=10)
        axes[2].set_title('Cell Size vs. Detection Quality')
        axes[2].set_xlabel('Pixel Area'); axes[2].set_ylabel('Object IoU')
        axes[2].set_xscale('log')
    else:
        axes[2].text(0.5, 0.5, "No Objects Found", ha='center')

    plt.tight_layout()
    plt.show()

# --- 4. VISUALIZATION GRID ---
print("\n🧠 INTERPRETABILITY GRID")
def make_gradcam(img_tensor, model, layer_name):
    grad_model = Model(model.inputs, [model.get_layer(layer_name).output, model.output])
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_tensor)
        if isinstance(predictions, list): predictions = predictions[-1]
        loss = predictions[:, :, :, 0]
    grads = tape.gradient(loss, conv_outputs)
    if grads is None: return np.zeros((512,512))
    weights = tf.reduce_mean(grads[0], axis=(0, 1))
    cam = tf.reduce_sum(tf.multiply(weights, conv_outputs[0]), axis=-1)
    cam = tf.maximum(cam, 0)
    return cv2.resize(cam.numpy(), (512, 512))

valid_data = [d for d in vault_data if d['iou'] > 0.1]
valid_data.sort(key=lambda x: x['iou'])
display_set = valid_data[-3:][::-1] + valid_data[:3]

if display_set:
    fig, axes = plt.subplots(len(display_set), 4, figsize=(16, 4*len(display_set)))
    if len(display_set) == 1: axes = [axes]

    cols = ["Input", "Truth", "Pred", "Grad-CAM"]
    for ax, col in zip(axes[0], cols): ax.set_title(col, fontsize=12, fontweight='bold')

    for i, item in enumerate(display_set):
        display_img = np.clip(item['img'] * IMAGENET_STD + IMAGENET_MEAN, 0, 1)
        row_axes = axes[i] if len(display_set) > 1 else axes

        row_axes[0].imshow(display_img)
        row_axes[0].set_ylabel(f"IoU: {item['iou']:.2f}")
        row_axes[1].imshow(item['true'], cmap='gray')
        row_axes[2].imshow(item['pred'], cmap='viridis')

        try:
            heatmap = make_gradcam(np.expand_dims(item['img'], 0), model, GRAD_CAM_LAYER)
            row_axes[3].imshow(display_img)
            row_axes[3].imshow(heatmap, cmap='jet', alpha=0.5)
        except: row_axes[3].text(0.5, 0.5, "Error", ha='center')

        for ax in row_axes: ax.set_xticks([]); ax.set_yticks([])

    plt.tight_layout()
    plt.show()
else:
    print("Not enough valid predictions to generate grid.")

# CELL 12: DEEP DIVE DIAGNOSTIC (Fixed for Native DenseNet)
import matplotlib.cm as cm
from sklearn.metrics import auc
from tensorflow.keras.layers import Conv2D, Conv2DTranspose

print("🔬 STARTING DEEP DIAGNOSTIC...")

# 1. ROBUST LAYER SEARCH (Find the last decoder layer)
# In our manual DenseNet build, layers are likely named 'conv2d_transpose_X' or similar.
target_layer = None
potential_layers = []

for layer in model.layers:
    # Look for Conv2DTranspose (Upsampling)
    if isinstance(layer, Conv2DTranspose):
        potential_layers.append(layer.name)

# We want the last upsampling block before the final head
if len(potential_layers) >= 2:
    GRAD_CAM_LAYER = potential_layers[-1]
else:
    # Fallback: grab the 2nd to last layer of the entire model
    GRAD_CAM_LAYER = model.layers[-2].name

print(f"   -> Using Layer: {GRAD_CAM_LAYER}")

# 2. GRAD-CAM FUNCTION
def make_gradcam(img_tensor, model, layer_name):
    # Output is now a single tensor, not a list
    grad_model = Model(model.inputs, [model.get_layer(layer_name).output, model.output])

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_tensor)
        # Handle list vs tensor just in case
        if isinstance(predictions, list): predictions = predictions[-1]

        loss = predictions[:, :, :, 0]

    grads = tape.gradient(loss, conv_outputs)
    if grads is None: return np.zeros((512,512)) # Safety

    grads = grads[0]
    weights = tf.reduce_mean(grads, axis=(0, 1))
    cam = tf.reduce_sum(tf.multiply(weights, conv_outputs[0]), axis=-1)
    cam = tf.maximum(cam, 0)
    cam = cam / (tf.reduce_max(cam) + 1e-6)
    return cv2.resize(cam.numpy(), (512, 512))

# 3. VISUALIZATION
# Re-using vault_metrics from Cell 9
valid_indices = [i for i, m in enumerate(vault_metrics) if m['iou'] > 0]
display_indices = valid_indices[:3] + valid_indices[-3:] if len(valid_indices) > 6 else valid_indices

fig, axes = plt.subplots(len(display_indices), 4, figsize=(16, 4 * len(display_indices)))
if len(display_indices) == 1: axes = [axes] # Handle single row case

for row_idx, i in enumerate(display_indices):
    item = vault_metrics[i]
    img_path = item['path']
    mask_path = vault_mask[vault_img.index(img_path)]

    img, true_mask = load_and_process(img_path.encode('utf-8'), mask_path.encode('utf-8'))

    # Predict & Squeeze
    preds = model.predict(np.expand_dims(img, 0), verbose=0)
    if isinstance(preds, list): preds = preds[-1]
    pred_prob = preds[0,:,:,0] # 2D

    # Display
    display_img = np.clip(img * IMAGENET_STD + IMAGENET_MEAN, 0, 1)

    # Input
    ax = axes[row_idx][0] if len(display_indices) > 1 else axes[0]
    ax.imshow(display_img)
    ax.set_ylabel(f"IoU: {item['iou']:.2f}")

    # Truth
    ax = axes[row_idx][1] if len(display_indices) > 1 else axes[1]
    ax.imshow(np.squeeze(true_mask), cmap='gray')

    # Pred
    ax = axes[row_idx][2] if len(display_indices) > 1 else axes[2]
    ax.imshow(pred_prob, cmap='viridis')

    # Grad-CAM
    ax = axes[row_idx][3] if len(display_indices) > 1 else axes[3]
    try:
        heatmap = make_gradcam(np.expand_dims(img, 0), model, GRAD_CAM_LAYER)
        ax.imshow(display_img)
        ax.imshow(heatmap, cmap='jet', alpha=0.5)
    except: ax.text(0.5, 0.5, "Grad-CAM Error", ha='center')

plt.tight_layout()
plt.show()