# -*- coding: utf-8 -*-
"""CHANA UNet++ without Domains

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lrqB8uYSSh2WYFaUw3Q90FIwLnOy3Kd

## CHANA UNet++

A 3 phase domain adaptation implementation on a TransUNet architecture including 1. diffusionn based synthetic images 2. copy paste augmentation and 3. real data that is expert labelled. Total dataset size should be around 6.5k images.
"""

# CELL 1: ENVIRONMENT & IMPORTS
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations keras-unet-collection
!pip install -q scikit-image opencv-python matplotlib tensorflow segmentation_models seaborn imagecodecs albumentations

import os
# Force float32 for stability
os.environ["SM_FRAMEWORK"] = "tf.keras"
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, Model, Input
from tensorflow.keras import mixed_precision
import segmentation_models as sm
import seaborn as sns
import pandas as pd
from skimage import io, measure, morphology
from scipy import ndimage
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve, average_precision_score
import gc

# Mount Drive
from google.colab import drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- GLOBAL STABILITY SETTINGS ---
tf.config.experimental.enable_tensor_float_32_execution(True)
mixed_precision.set_global_policy('float32')
print(f"✅ TensorFlow {tf.__version__} Ready. Global Policy: Float32")



# CELL 2: CONFIGURATION & CURRICULUM (DenseNet121 / 500 Epochs)
PROJECT_BASE_PATH = '/content/drive/MyDrive/CHANA_files'

# --- PATHS ---
PREPROCESSED_IMAGES_DIR = os.path.join(PROJECT_BASE_PATH, 'preprocessed_rgb')
GROUND_TRUTH_MASKS_DIR = os.path.join(PROJECT_BASE_PATH, 'mask_images_512')

# (Synthetic paths unused in this run)
DIFFUSION_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_training_data_v2_ancestral')
COPYPASTE_DIR = os.path.join(PROJECT_BASE_PATH, 'synthetic_experiment/generated_images')
PSEUDO_DIR = os.path.join(PROJECT_BASE_PATH, 'pseudo_train_data', 'images')

# --- 📅 THE CURRICULUM SCHEDULE ---
CURRICULUM_PLAN = [
    {
        "stage": 3,
        "name": "Phase 3: Real Fine-Tuning (Long Run)",
        "description": "Standard U-Net (DenseNet) on Real Data",
        "data_dir": PREPROCESSED_IMAGES_DIR,
        "data_type": "real",
        "epochs": 500,          # <--- INCREASED TO 500
        "init_lr": 1e-4,
        "loss_strategy": "robust",
        # 🏆 SAVE NAME
        "save_path": os.path.join(PROJECT_BASE_PATH, 'Unetplusplus_withoutDomain.weights.h5')
    }
]

# Config
IMG_HEIGHT, IMG_WIDTH = 512, 512
IMG_CHANNELS = 3
NUM_CLASSES = 1
BATCH_SIZE = 16

print("🚀 CONFIGURATION READY: DenseNet121 (500 Epochs)")

# CELL 3: DATA LOADING UTILITIES
import albumentations as A

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def preprocess_input_v7(img):
    img = img.astype(np.float32) / 255.0
    img = (img - IMAGENET_MEAN) / IMAGENET_STD
    return img

aug_pipeline = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=20, p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.CoarseDropout(max_holes=6, max_height=24, max_width=24, p=0.3),
])

def augment_data(img, mask):
    aug = aug_pipeline(image=img, mask=mask)
    return aug['image'], aug['mask']

def load_and_process(img_path, mask_path):
    path_str = img_path.decode('utf-8')
    try:
        img = cv2.imread(path_str, cv2.IMREAD_COLOR)
        if img is None: # Fallback for TIF/Special formats
            img = io.imread(path_str)
            if img.ndim == 2: img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
            elif img.shape[2] == 4: img = img[:,:,:3]
    except:
        return np.zeros((512,512,3), dtype=np.float32), np.zeros((512,512,1), dtype=np.float32)

    if img is not None:
        if path_str.lower().endswith(('.png', '.jpg')):
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = cv2.resize(img, (512, 512), interpolation=cv2.INTER_AREA)
    img = preprocess_input_v7(img)

    m_path_str = mask_path.decode('utf-8')
    if m_path_str.endswith('.tif'): mask = io.imread(m_path_str)
    else: mask = cv2.imread(m_path_str, cv2.IMREAD_GRAYSCALE)
    if mask is None: mask = io.imread(m_path_str)

    if mask.shape[:2] != (512, 512):
        mask = cv2.resize(mask, (512, 512), interpolation=cv2.INTER_NEAREST)

    mask = (mask > 0).astype(np.float32)
    if mask.ndim == 2: mask = np.expand_dims(mask, axis=-1)

    return img, mask

def create_tf_dataset(images, masks, training=True):
    ds = tf.data.Dataset.from_tensor_slices((images, masks))
    ds = ds.shuffle(len(images)) if training else ds
    ds = ds.repeat()

    ds = ds.map(lambda i, m: tf.numpy_function(load_and_process, [i, m], [tf.float32, tf.float32]),
                num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.map(lambda i, m: tf.numpy_function(augment_data, [i, m], [tf.float32, tf.float32]),
                    num_parallel_calls=tf.data.AUTOTUNE)

    # UPDATED FOR TRUE DEEP SUPERVISION (4 Outputs, All Full Res)
    def format_output(i, m):
        i = tf.ensure_shape(i, [512, 512, 3])
        m = tf.ensure_shape(m, [512, 512, 1])
        # UNet++ (depth 4) with deep supervision produces 4 outputs at level 0.
        # All of them are 512x512. We just replicate the mask.
        return i, (m, m, m, m)

    ds = ds.map(format_output, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

# CELL 4: ARCHITECTURE (UNet++ with ResNet50)
# ==============================================================================

from keras_unet_collection import models as unet_models
from tensorflow.keras import layers, Model

def build_custom_unet(input_shape, num_classes):
    print(f"🏗️ Building Native U-Net++ (ResNet50) with Deep Supervision...")

    # 1. Build the model with native Deep Supervision enabled
    # - activation='ReLU': Standard for hidden layers (Fixes the crash)
    # - output_activation='sigmoid': Standard for binary mask output
    model = unet_models.unet_plus_2d(
        input_size=input_shape,
        filter_num=[64, 128, 256, 512],
        n_labels=num_classes,
        stack_num_down=4,
        stack_num_up=4,
        activation='ReLU',          # <--- CHANGED from 'Sigmoid' (Fixes NameError)
        output_activation='Sigmoid',# <--- CHANGED to lowercase 'sigmoid'
        batch_norm=True,
        pool=False,
        unpool=False,
        backbone='ResNet50',
        weights='imagenet',
        freeze_backbone=False,
        freeze_batch_norm=False,
        deep_supervision=True
    )

    print(f"✅ Architecture Ready.")
    print(f"   -> Backbone: ResNet50 (ImageNet Weights)")
    print(f"   -> Deep Supervision Heads: {len(model.outputs)}")

    return model

# CELL 5: DYNAMIC LOSS STRATEGIES
import tensorflow.keras.backend as K

# Strategy 1: "Robust" (Focal Tversky) - For Trusted Labels
def focal_tversky_loss(y_true, y_pred, alpha=0.3, beta=0.7, gamma=1.5):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    tp = K.sum(y_true_f * y_pred_f)
    fn = K.sum(y_true_f * (1 - y_pred_f))
    fp = K.sum((1 - y_true_f) * y_pred_f)
    tversky = (tp + 1e-6) / (tp + alpha * fn + beta * fp + 1e-6)
    return K.pow((1 - tversky), gamma)

# Strategy 2: "Soft" (BCE + Label Smoothing) - For Noisy Labels/Arrogant Models
def soft_bce_loss(y_true, y_pred):
    # Standard BCE with label smoothing (0.1 means target becomes 0.95/0.05)
    return tf.keras.losses.binary_crossentropy(y_true, y_pred, label_smoothing=0.1)

def dice_loss_fn(y_true, y_pred):
    smooth = 1e-6
    intersection = K.sum(y_true * y_pred)
    return 1 - (2. * intersection + smooth) / (K.sum(y_true) + K.sum(y_pred) + smooth)

common_metrics = [sm.metrics.iou_score, sm.metrics.f1_score]

# CELL 6: "THE VAULT" - STRICT DATA SPLITTING
print("🚜 Harvesting Real Data...")
all_real_img, all_real_mask = [], []

# 1. Harvest
for f in os.listdir(PREPROCESSED_IMAGES_DIR):
    if f.lower().endswith(('.png', '.tif', '.jpg')):
        base = os.path.splitext(f)[0]
        # Robust mask finding
        for ext in ['_mask.tif', '_mask.png', '.tif', '.png']:
            p = os.path.join(GROUND_TRUTH_MASKS_DIR, base + ext)
            if os.path.exists(p):
                all_real_img.append(os.path.join(PREPROCESSED_IMAGES_DIR, f))
                all_real_mask.append(p)
                break

# 2. Split 1: Isolate The Vault (15%)
remaining_img, vault_img, remaining_mask, vault_mask = train_test_split(
    all_real_img, all_real_mask, test_size=0.15, random_state=999 # Fixed seed
)

# 3. Split 2: Train vs Val (Validation 15% of original, approx 17% of remaining)
train_real_img, val_real_img, train_real_mask, val_real_mask = train_test_split(
    remaining_img, remaining_mask, test_size=0.176, random_state=42
)

print(f"🔒 THE VAULT (Test Set) Sealed: {len(vault_img)} images.")
print(f"📖 Validation Set Ready:       {len(val_real_img)} images.")
print(f"🏋️ Training Set Ready:         {len(train_real_img)} images.")

# Create the Validation Dataset ONCE for consistency
val_dataset = create_tf_dataset(val_real_img, val_real_mask, training=False)
STEPS_PER_EPOCH_VAL = len(val_real_img) // BATCH_SIZE

# Save Vault list
with open('VAULT_FILES.txt', 'w') as f:
    for item in vault_img: f.write(f"{item}\n")

# CELL 7: OBJECT-LEVEL METRICS CALLBACK (TRAINING MONITOR)
from tensorflow.keras.callbacks import Callback

class ObjectMetricsCallback(Callback):
    def __init__(self, val_images, val_masks, freq=1):
        super().__init__()
        self.val_images = val_images[:100] # Check first 100 for speed
        self.val_masks = val_masks[:100]
        self.freq = freq

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.freq != 0: return

        total_tp, total_fp, total_fn = 0, 0, 0
        min_area = 50

        # Run inference on subset
        for i, img_p in enumerate(self.val_images):
            try:
                # Load (Re-using helper)
                img, true_mask = load_and_process(img_p.encode('utf-8'), self.val_masks[i].encode('utf-8'))

                # Predict
                pred_prob = self.model.predict(np.expand_dims(img, 0), verbose=0)[0][0]

                # Threshold & Process
                p_mask = np.squeeze((pred_prob > 0.5).astype(np.uint8))
                p_mask = ndimage.binary_fill_holes(p_mask).astype(np.uint8)
                t_mask = np.squeeze((true_mask > 0.5).astype(np.uint8))

                # Count
                p_cents = [r.centroid for r in measure.regionprops(measure.label(p_mask)) if r.area > min_area]
                t_cents = [r.centroid for r in measure.regionprops(measure.label(t_mask)) if r.area > min_area]

                # Match
                matches = 0
                if t_cents and p_cents:
                    dists = cdist(t_cents, p_cents)
                    rows, cols = linear_sum_assignment(dists)
                    for r, c in zip(rows, cols):
                        if dists[r, c] < 25: matches += 1

                total_tp += matches
                total_fp += len(p_cents) - matches
                total_fn += len(t_cents) - matches
            except: pass

        # Calc Metrics
        prec = total_tp / (total_tp + total_fp + 1e-6)
        rec = total_tp / (total_tp + total_fn + 1e-6)
        f1 = 2 * prec * rec / (prec + rec + 1e-6)

        print(f"\n   🎯 [Epoch {epoch+1}] Object Metrics -> F1: {f1:.4f} | Prec: {prec:.4f} | Rec: {rec:.4f}")
        logs['val_object_f1'] = f1

# CELL 8: THE MASTER TRAINING LOOP (Robust V9.0)
from tensorflow.keras.optimizers import AdamW

# 1. Initialize Model
tf.keras.backend.clear_session()
gc.collect()
model = build_custom_unet(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), num_classes=NUM_CLASSES)
print("🏗️ Model Initialized.")

# --- AUTO-ADAPT LOGIC ---
# Detect actual model outputs (Your log said 3, previous code expected 4)
NUM_MODEL_OUTPUTS = len(model.outputs)
print(f"⚙️ Auto-Detected Model Outputs: {NUM_MODEL_OUTPUTS}")

# Helper to trim data if the generator produces more masks than the model needs
def adapt_data_to_model(image, masks_tuple):
    # Slice the tuple of masks to match the model's output count
    return image, masks_tuple[:NUM_MODEL_OUTPUTS]

# 2. Iterate Curriculum
for plan in CURRICULUM_PLAN:
    print(f"\n" + "="*60)
    print(f"🎬 STARTING {plan['name']}")
    print("="*60)

    # A. Dynamic Data Loading
    current_train_img, current_train_mask = [], []

    if plan['data_type'] == 'diffusion':
        for f in os.listdir(plan['data_dir']):
            if f.endswith('_image.png'):
                mask_p = os.path.join(plan['data_dir'], f.replace('_image.png', '_mask.png'))
                if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'copypaste':
        base_dir = os.path.dirname(plan['data_dir'])
        cp_mask_dir = os.path.join(base_dir, 'generated_masks')
        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg')):
                possible_names = [f, f.replace('.png', '_mask.png'), f.replace('.jpg', '_mask.png')]
                for m_name in possible_names:
                    mask_p = os.path.join(cp_mask_dir, m_name)
                    if os.path.exists(mask_p):
                        current_train_img.append(os.path.join(plan['data_dir'], f))
                        current_train_mask.append(mask_p)
                        break

    elif plan['data_type'] == 'pseudo':
        base_dir = os.path.dirname(plan['data_dir'])
        pseudo_mask_dir = os.path.join(base_dir, 'masks')
        if not os.path.exists(pseudo_mask_dir): print(f"⚠️ WARNING: Pseudo mask dir not found at {pseudo_mask_dir}")
        for f in os.listdir(plan['data_dir']):
            if f.lower().endswith(('.png', '.jpg', '.tif')):
                 mask_p = os.path.join(pseudo_mask_dir, f)
                 if not os.path.exists(mask_p): mask_p = os.path.join(pseudo_mask_dir, os.path.splitext(f)[0] + "_mask.png")
                 if not os.path.exists(mask_p): mask_p = os.path.join(pseudo_mask_dir, os.path.splitext(f)[0] + ".tif")
                 if os.path.exists(mask_p):
                    current_train_img.append(os.path.join(plan['data_dir'], f))
                    current_train_mask.append(mask_p)

    elif plan['data_type'] == 'real':
        current_train_img = train_real_img
        current_train_mask = train_real_mask

    print(f"   -> Found {len(current_train_img)} training pairs.")

    if len(current_train_img) == 0:
        print(f"❌ CRITICAL ERROR: No data found for {plan['name']}. Check paths!")
        continue

    # Create Dataset
    train_ds = create_tf_dataset(current_train_img, current_train_mask, training=True)

    # --- DATA ADAPTER (The Fix for 4 vs 3 outputs) ---
    # This prevents "ValueError: Expects 3 arrays, found 4"
    train_ds = train_ds.map(adapt_data_to_model, num_parallel_calls=tf.data.AUTOTUNE)

    # Also adapt validation set
    val_ds_adapted = val_dataset.map(adapt_data_to_model, num_parallel_calls=tf.data.AUTOTUNE)

    steps_per_epoch = len(current_train_img) // BATCH_SIZE

    # B. Compile with Dynamic Loss & LR
    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=plan['init_lr'],
        decay_steps=plan['epochs'] * steps_per_epoch,
        alpha=0.05
    )
    optimizer = AdamW(learning_rate=lr_schedule, weight_decay=1e-4)

    # SELECT LOSS FUNCTION & ADJUST FOR OUTPUT COUNT
    if plan['loss_strategy'] == 'soft':
        primary_loss = soft_bce_loss
        base_weights = [1.0, 0.5, 0.4, 0.3]
    else:
        primary_loss = focal_tversky_loss
        base_weights = [1.0, 0.4, 0.3, 0.2]

    # Dynamically slice lists to match NUM_MODEL_OUTPUTS (e.g., take first 3)
    active_losses = [primary_loss] + [dice_loss_fn] * (NUM_MODEL_OUTPUTS - 1)
    active_weights = base_weights[:NUM_MODEL_OUTPUTS]
    active_metrics = [common_metrics] * NUM_MODEL_OUTPUTS

    model.compile(
        optimizer=optimizer,
        loss=active_losses,
        loss_weights=active_weights,
        metrics=active_metrics
    )

    # C. Callbacks
    # FIXED: Monitor 'val_loss' to be safe against layer name changes
    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            plan['save_path'], monitor='val_loss', mode='min',
            save_best_only=True, save_weights_only=True, verbose=1
        ),
        ObjectMetricsCallback(val_real_img, val_real_mask, freq=2)
    ]

    if plan['stage'] == 3:
        callbacks.append(tf.keras.callbacks.EarlyStopping(
            monitor='val_loss', mode='min', patience=35, restore_best_weights=True, verbose=1
        ))

    # FIXED: Removed __file__ reference for Colab compatibility
    log_name = f"log_{plan['name'].replace(' ', '_')}_training.csv"
    callbacks.append(tf.keras.callbacks.CSVLogger(os.path.join(PROJECT_BASE_PATH, log_name)))

    # D. Train
    model.fit(
        train_ds,
        steps_per_epoch=steps_per_epoch,
        epochs=plan['epochs'],
        validation_data=val_ds_adapted, # Use the adapted validation set
        validation_steps=STEPS_PER_EPOCH_VAL,
        callbacks=callbacks
    )

    # E. Handover
    print(f"✅ {plan['name']} Complete. Loading best weights...")
    model.load_weights(plan['save_path'])

print("\n🏆 DOMAIN ADAPTATION CURRICULUM COMPLETE.")

# CELL 9: "THE VAULT" PIXEL EVALUATION (Universal Fix)
import pandas as pd
import os
import numpy as np

print("⚖️ UNLOCKING THE VAULT: Final Evaluation...")

# 1. SETUP PATHS
# Ensure this matches the save_path you defined in Cell 2
model_filename = 'Unetplusplus_withoutDomain.weights.h5'
final_model_path = os.path.join(PROJECT_BASE_PATH, model_filename)

# 2. LOAD WEIGHTS
print(f"   -> Loading weights from: {model_filename}")
try:
    model.load_weights(final_model_path)
    print("✅ Weights loaded successfully.")
except FileNotFoundError:
    print(f"❌ ERROR: Could not find file {final_model_path}")
    print("   Did Cell 8 finish training?")

# 3. RUN INFERENCE
vault_metrics = []
print(f"   -> Processing {len(vault_img)} unseen test images...")

for i, img_path in enumerate(vault_img):
    try:
        # UNIVERSAL FIX 1: Handle String vs Bytes for Path
        # We try to encode; if it's already bytes, we use it as is.
        if isinstance(img_path, str):
            p_img = img_path.encode('utf-8')
            p_mask = vault_mask[i].encode('utf-8')
        else:
            p_img = img_path
            p_mask = vault_mask[i]

        img, true_mask = load_and_process(p_img, p_mask)

        # Predict
        preds = model.predict(np.expand_dims(img, 0), verbose=0)

        # UNIVERSAL FIX 2: Handle Deep Supervision (List) vs Standard (Tensor)
        if isinstance(preds, list):
            # U-Net++ returns [output, ds1, ds2, ds3]. We want the first one (Main).
            # Note: Verify if your specific U-Net++ implementation puts main first or last.
            # Usually 'output' is first or last. We check shape to be safe.
            raw_pred = preds[0]
        else:
            raw_pred = preds

        # UNIVERSAL FIX 3: Squeeze to 2D
        pred_prob = np.squeeze(raw_pred)
        if pred_prob.ndim == 3: pred_prob = pred_prob[..., 0]

        # Prepare Masks
        p_mask_bin = (pred_prob > 0.5).astype(np.float32)

        t_mask = np.squeeze(true_mask)
        if t_mask.ndim == 3: t_mask = t_mask[..., 0]
        t_mask_bin = (t_mask > 0.5).astype(np.float32)

        # Calculate IoU
        intersection = np.sum(t_mask_bin * p_mask_bin)
        union = np.sum(t_mask_bin) + np.sum(p_mask_bin) - intersection

        if np.sum(t_mask_bin) == 0 and np.sum(p_mask_bin) == 0:
            iou = 1.0
        else:
            iou = intersection / (union + 1e-6)

        vault_metrics.append({'path': img_path, 'iou': iou})

    except Exception as e:
        if i < 3: print(f"Error on image {i}: {e}")

# 4. REPORT
if len(vault_metrics) > 0:
    df_vault = pd.DataFrame(vault_metrics)
    print("\n" + "="*40)
    print(f"🏛️ FINAL TEST SET (VAULT) REPORT")
    print(f"   Model: {model_filename}")
    print("="*40)
    print(f"Mean IoU: {df_vault['iou'].mean():.4f}")
    print("="*40)
else:
    print("\n❌ CRITICAL: No metrics generated. All images failed processing.")

# CELL 10: HUNGARIAN MATCHING & VISUALIZATION (Deep Sup Corrected)
print("\n--- Object-Level Evaluation (Vault) ---")

# --- CONFIG ---
MIN_AREA = 50
MAX_DISTANCE = 25
SAMPLE_LIMIT = 50

# --- DATA TARGETING ---
target_img_list = vault_img
target_mask_list = vault_mask

# --- HELPER: Plotting ---
def plot_object_detection(img, t_cents, p_cents, matches):
    display_img = np.clip(img * IMAGENET_STD + IMAGENET_MEAN, 0, 1)

    plt.figure(figsize=(8, 8))
    plt.imshow(display_img)

    # Truth (Blue)
    if len(t_cents) > 0:
        t_arr = np.array(t_cents)
        plt.plot(t_arr[:, 1], t_arr[:, 0], 'bo', markersize=10, fillstyle='none', markeredgewidth=2, label='Truth')

    # Pred (Red)
    if len(p_cents) > 0:
        p_arr = np.array(p_cents)
        plt.plot(p_arr[:, 1], p_arr[:, 0], 'rx', markersize=10, markeredgewidth=2, label='Pred')

    # Matches (Green)
    for t_idx, p_idx in matches:
        tr, tc = t_cents[t_idx]
        pr, pc = p_cents[p_idx]
        plt.plot([tc, pc], [tr, pr], 'g-', linewidth=2, alpha=0.7)

    plt.legend(loc='upper right')
    plt.title("Blue=Truth, Red=Pred, Green=Match")
    plt.axis('off')
    plt.show()

# --- EXECUTION ---
total_tp, total_fp, total_fn = 0, 0, 0

for i, img_path in enumerate(target_img_list[:SAMPLE_LIMIT]):
    try:
        # Load
        img, true_mask = load_and_process(img_path.encode('utf-8'), target_mask_list[i].encode('utf-8'))

        # Predict (FIXED FOR DEEP SUPERVISION)
        preds = model.predict(np.expand_dims(img, 0), verbose=0)
        if isinstance(preds, list):
            pred_prob = preds[-1][0] # Final Output
        else:
            pred_prob = preds[0]

        # Process
        p_mask_2d = np.squeeze((pred_prob > 0.5).astype(np.uint8))
        t_mask_2d = np.squeeze((true_mask > 0.5).astype(np.uint8))
        p_mask_2d = ndimage.binary_fill_holes(p_mask_2d).astype(np.uint8)

        # Get Centroids
        p_props = measure.regionprops(measure.label(p_mask_2d))
        p_cents = [r.centroid for r in p_props if MIN_AREA < r.area < 10000]

        t_props = measure.regionprops(measure.label(t_mask_2d))
        t_cents = [r.centroid for r in t_props if MIN_AREA < r.area < 10000]

        # Match (Hungarian)
        matches = []
        tp_curr = 0

        if len(t_cents) > 0 and len(p_cents) > 0:
            t_arr = np.array(t_cents)
            p_arr = np.array(p_cents)
            dists = cdist(t_arr, p_arr)
            rows, cols = linear_sum_assignment(dists)

            for row, col in zip(rows, cols):
                if dists[row, col] < MAX_DISTANCE:
                    matches.append((row, col))
                    tp_curr += 1

        fp_curr = len(p_cents) - tp_curr
        fn_curr = len(t_cents) - tp_curr

        total_tp += tp_curr
        total_fp += fp_curr
        total_fn += fn_curr

        # Visualize first 3
        if i < 3 and (t_cents or p_cents):
            plot_object_detection(img, t_cents, p_cents, matches)

    except Exception as e: print(f"Skip: {e}")

# --- METRICS ---
precision = total_tp / (total_tp + total_fp + 1e-6)
recall = total_tp / (total_tp + total_fn + 1e-6)
f1 = 2 * precision * recall / (precision + recall + 1e-6)

print("\n" + "="*40)
print(f"🎯 OBJECT-LEVEL METRICS (VAULT)")
print("="*40)
print(f"Global F1 Score: {f1:.4f}")
print(f"Global Precision: {precision:.4f}")
print(f"Global Recall:    {recall:.4f}")
print("="*40)

# CELL 11: SIZE BIN ANALYSIS (Deep Sup Corrected)
print("--- Deep Diagnostics by Object Size (Vault) ---")

# --- CONFIG ---
SIZE_BINS = [0, 500, 1500, 10000]
BIN_LABELS = ['Small', 'Medium', 'Large']
object_data = []

# --- EXECUTION ---
if vault_img:
    for i, img_path in enumerate(vault_img[:100]):
        try:
            img, true_mask = load_and_process(img_path.encode('utf-8'), vault_mask[i].encode('utf-8'))

            # Predict (FIXED FOR DEEP SUPERVISION)
            preds = model.predict(np.expand_dims(img, 0), verbose=0)
            if isinstance(preds, list):
                pred_prob = preds[-1][0]
            else:
                pred_prob = preds[0]

            p_mask = (pred_prob > 0.5).astype(np.uint8)
            t_mask = (true_mask > 0.5).astype(np.uint8)
            if t_mask.ndim == 3: t_mask = t_mask[:,:,0]

            true_labels = measure.label(t_mask, connectivity=2)
            for t_region in measure.regionprops(true_labels):
                if t_region.area < 50: continue

                t_mask_iso = (true_labels == t_region.label)
                intersection = np.logical_and(t_mask_iso, p_mask).sum()
                coverage = intersection / t_region.area

                object_data.append({
                    'Area': t_region.area,
                    'Detected': coverage > 0.5,
                    'IoU': coverage
                })
        except: pass

    if object_data:
        obj_df = pd.DataFrame(object_data)
        obj_df['Size_Bin'] = pd.cut(obj_df['Area'], bins=SIZE_BINS, labels=BIN_LABELS)

        print("\nDetection Rate by Size:")
        print(obj_df.groupby('Size_Bin')['Detected'].mean())

        plt.figure(figsize=(8, 5))
        sns.barplot(data=obj_df, x='Size_Bin', y='Detected', palette='viridis')
        plt.title("Probability of Detecting a Cell vs. Cell Size")
        plt.ylabel("Detection Probability")
        plt.ylim(0, 1.0)
        plt.grid(axis='y', alpha=0.3)
        plt.show()
    else:
        print("No objects found to analyze.")

import matplotlib.cm as cm
from sklearn.metrics import auc, precision_recall_curve
from tensorflow.keras.models import Model
import cv2

print("🔬 STARTING DEEP DIAGNOSTIC (UNet++ Deep Supervision Mode)...")

# --- CONFIG ---
# Target the last upsampling layer.
GRAD_CAM_LAYER = 'conv2d_transpose_3'
if GRAD_CAM_LAYER not in [l.name for l in model.layers]:
    # Fallback: search for the last conv2d_transpose layer
    possible_layers = [l.name for l in model.layers if 'conv2d_transpose' in l.name]
    GRAD_CAM_LAYER = possible_layers[-1] if possible_layers else None
    print(f"   -> Default layer not found. Switching Grad-CAM to: {GRAD_CAM_LAYER}")

# --- 1. HARVEST METRICS ---
vault_data = []
all_true_flat = []
all_pred_flat = []
object_sizes = []
object_ious = []

print(f"   -> Analyzing {len(vault_img)} test images...")

for i, img_path in enumerate(vault_img):
    try:
        # FIX: Encode strings to bytes for load_and_process
        img, true_mask = load_and_process(
            img_path.encode('utf-8'),
            vault_mask[i].encode('utf-8')
        )

        # --- INFERENCE (DEEP SUPERVISION FIX) ---
        raw_pred = model.predict(np.expand_dims(img, 0), verbose=0)
        if isinstance(raw_pred, list):
            pred_prob = raw_pred[0][0] # Deep supervision: Index 0 is final output
        else:
            pred_prob = raw_pred[0]

        pred_mask = (pred_prob > 0.5).astype(np.float32)

        # Pixel Stats
        intersection = np.sum(true_mask * pred_mask)
        union = np.sum(true_mask) + np.sum(pred_mask) - intersection
        iou = intersection / (union + 1e-6)

        # Store for Global Metrics
        all_true_flat.extend(true_mask.flatten())
        all_pred_flat.extend(pred_prob.flatten())

        # Object Analysis (Size vs IoU)
        t_labeled = measure.label(true_mask[:,:,0])
        for region in measure.regionprops(t_labeled):
            if region.area < 50: continue
            obj_mask = (t_labeled == region.label).astype(np.float32)

            # Intersection with prediction
            obj_int = np.sum(obj_mask * pred_mask[:,:,0])
            # Local IoU
            obj_iou = obj_int / (np.sum(obj_mask) + np.sum(pred_mask[:,:,0] * obj_mask) + 1e-6)

            object_sizes.append(region.area)
            object_ious.append(obj_iou)

        vault_data.append({
            'id': i,
            'img': img,
            'true': true_mask,
            'pred': pred_prob,
            'iou': iou,
            'has_osteoclast': np.sum(true_mask) > 0
        })

    except Exception as e: print(f"Error on {i}: {e}")

# --- 2. GLOBAL PIXEL METRICS ---
print("\n" + "="*40)
print("📊 GLOBAL PIXEL-LEVEL REPORT")
print("="*40)
y_true = np.array(all_true_flat) > 0.5
y_scores = np.array(all_pred_flat)
y_pred_hard = y_scores > 0.5

g_tp = np.sum(y_true & y_pred_hard)
g_fp = np.sum((~y_true) & y_pred_hard)
g_fn = np.sum(y_true & (~y_pred_hard))

g_prec = g_tp / (g_tp + g_fp + 1e-6)
g_rec = g_tp / (g_tp + g_fn + 1e-6)
g_f1 = 2 * g_prec * g_rec / (g_prec + g_rec + 1e-6)
g_iou = g_tp / (g_tp + g_fp + g_fn + 1e-6)

print(f"Global Pixel F1:        {g_f1:.4f}")
print(f"Global Pixel IoU:       {g_iou:.4f}")
print(f"Global Pixel Precision: {g_prec:.4f}")
print(f"Global Pixel Recall:    {g_rec:.4f}")

# --- 3. PLOTS ---
fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# A. IoU Distribution
if vault_data:
    ious = [d['iou'] for d in vault_data]
    sns.histplot(ious, bins=20, kde=True, ax=axes[0], color='skyblue')
    axes[0].set_title('Distribution of IoU Scores (Test Set)')
    axes[0].set_xlabel('IoU')

    # B. Precision-Recall Curve
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    pr_auc = auc(recall, precision)
    axes[1].plot(recall, precision, color='purple', label=f'AP={pr_auc:.2f}')
    axes[1].set_title('Pixel Precision-Recall Curve')
    axes[1].set_xlabel('Recall')
    axes[1].set_ylabel('Precision')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    # C. Size vs IoU
    if object_sizes:
        axes[2].scatter(object_sizes, object_ious, alpha=0.4, color='teal', s=10)
        axes[2].set_title('Cell Size vs. Detection Quality')
        axes[2].set_xlabel('Cell Area (Pixels)')
        axes[2].set_ylabel('Object Overlap')
        axes[2].set_xscale('log')
    else:
        axes[2].text(0.5, 0.5, "No objects", ha='center')
plt.show()

# --- 4. INTERPRETABILITY GRID (GRAD-CAM & UNCERTAINTY) ---
# Filter only images with actual cells
valid_data = [d for d in vault_data if d['has_osteoclast']]
if valid_data:
    valid_data.sort(key=lambda x: x['iou'])

    top_5 = valid_data[-5:][::-1]
    bot_5 = valid_data[:5]
    display_set = top_5 + bot_5

    def make_gradcam(img_tensor, model, layer_name):
        # --- GRAD-CAM FIX FOR DEEP SUPERVISION ---
        # Explicitly target model.outputs[0] (the main output)
        primary_output = model.outputs[0] if isinstance(model.outputs, list) else model.output

        grad_model = Model([model.inputs], [model.get_layer(layer_name).output, primary_output])

        with tf.GradientTape() as tape:
            conv_outputs, predictions = grad_model(img_tensor)
            # predictions shape: (Batch, H, W, Channels). We want channel 0.
            loss = predictions[:, :, :, 0]

        output = conv_outputs[0]
        grads = tape.gradient(loss, conv_outputs)[0]

        weights = tf.reduce_mean(grads, axis=(0, 1))
        cam = tf.reduce_sum(tf.multiply(weights, output), axis=-1)

        cam = tf.maximum(cam, 0) # ReLU
        cam = cam / (tf.reduce_max(cam) + 1e-6) # Normalize
        cam = cam.numpy()
        cam = cv2.resize(cam, (512, 512))
        return cam

    print("\n" + "="*60)
    print(f"🧠 INTERPRETABILITY GRID (Top 5 vs Bottom 5 Performers)")
    print("="*60)

    fig, axes = plt.subplots(len(display_set), 5, figsize=(20, 4 * len(display_set)))
    cols = ["Input Image", "Ground Truth", "Prediction", "Saliency (Grad-CAM)", "Uncertainty (Entropy)"]

    if len(display_set) == 1: axes = [axes] # Handle edge case

    for ax, col in zip(axes[0], cols): ax.set_title(col, fontsize=14)

    for i, data in enumerate(display_set):
        row_label = "TOP 5 (Best)" if i < 5 else "BOT 5 (Worst)"

        # 1. Image
        display_img = np.clip(data['img'] * IMAGENET_STD + IMAGENET_MEAN, 0, 1)
        axes[i, 0].imshow(display_img)
        axes[i, 0].set_ylabel(f"{row_label}\nIoU: {data['iou']:.2f}", fontsize=12)

        # 2. Truth
        axes[i, 1].imshow(data['true'][:,:,0], cmap='gray')

        # 3. Pred
        axes[i, 2].imshow(data['pred'][:,:,0], cmap='viridis')

        # 4. Saliency (Grad-CAM)
        if GRAD_CAM_LAYER:
            try:
                input_tensor = np.expand_dims(data['img'], 0)
                heatmap = make_gradcam(input_tensor, model, GRAD_CAM_LAYER)
                axes[i, 3].imshow(display_img)
                axes[i, 3].imshow(heatmap, cmap='jet', alpha=0.5)
            except Exception as e:
                axes[i, 3].text(0.5, 0.5, f"Layer Error\n{e}", ha='center', fontsize=8)
        else:
             axes[i, 3].text(0.5, 0.5, "Grad-CAM Layer Not Found", ha='center')

        # 5. Uncertainty (Entropy)
        p = np.clip(data['pred'][:,:,0], 1e-6, 1-1e-6)
        entropy = - (p * np.log(p) + (1-p) * np.log(1-p))
        axes[i, 4].imshow(entropy, cmap='magma')

        for ax in axes[i]: ax.set_xticks([]); ax.set_yticks([])

    plt.tight_layout()
    plt.show()
else:
    print("No images with cells found in the Vault.")