# -*- coding: utf-8 -*-
"""CHANA Copy Paste Gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYmBeX9GAqSApdHJfc9Gr5XkOfiO6mxo
"""

import os
import shutil
import time
from tqdm.notebook import tqdm

# --- CONFIGURATION ---
DRIVE_BASE = '/content/drive/MyDrive/CHANA_files'
LOCAL_BASE = '/content/CHANA_local'  # Temporary fast storage

print(f"🚀 INITIALIZING HIGH-SPEED WORKFLOW...")

# 1. Define Paths
DRIVE_IMG = os.path.join(DRIVE_BASE, 'original_images')
DRIVE_MASK = os.path.join(DRIVE_BASE, 'mask_images_512')
LOCAL_IMG = os.path.join(LOCAL_BASE, 'original_images')
LOCAL_MASK = os.path.join(LOCAL_BASE, 'mask_images_512')

# 2. Check Connection
if not os.path.exists(DRIVE_IMG):
    raise FileNotFoundError(f"❌ CRITICAL: Could not find '{DRIVE_IMG}'. Check your Drive path!")

# 3. Copy Data to Local SSD (Only if not already there)
if not os.path.exists(LOCAL_IMG):
    print("📦 Caching data to Local SSD (This fixes the speed bottleneck)...")
    os.makedirs(LOCAL_IMG, exist_ok=True)
    os.makedirs(LOCAL_MASK, exist_ok=True)

    # Copy Images
    files = [f for f in os.listdir(DRIVE_IMG) if f.lower().endswith(('.png', '.jpg', '.tif', '.tiff'))]
    print(f"   -> Copying {len(files)} source images...")
    for f in tqdm(files, unit='img'):
        shutil.copy2(os.path.join(DRIVE_IMG, f), os.path.join(LOCAL_IMG, f))

    # Copy Masks
    masks = [f for f in os.listdir(DRIVE_MASK) if f.lower().endswith(('.png', '.tif'))]
    print(f"   -> Copying {len(masks)} source masks...")
    for f in tqdm(masks, unit='mask'):
        shutil.copy2(os.path.join(DRIVE_MASK, f), os.path.join(LOCAL_MASK, f))

    print("✅ Transfer Complete. Local SSD Ready.")
else:
    print("⚡ Data already cached locally. Skipping transfer.")

# Set Global Input Paths to the Fast Local Copy
INPUT_IMG_DIR = LOCAL_IMG
INPUT_MASK_DIR = LOCAL_MASK

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, measure

# --- OUTPUT CONFIG ---
# We store intermediate assets (chips) locally for speed
ASSET_BASE = os.path.join(LOCAL_BASE, 'assets')
CELL_BANK = os.path.join(ASSET_BASE, 'cell_bank')
BG_BANK = os.path.join(ASSET_BASE, 'bg_bank')

# Setup Directories
for d in [CELL_BANK, BG_BANK]:
    if os.path.exists(d): shutil.rmtree(d) # Clean slate
    os.makedirs(d, exist_ok=True)

# Parameters
MIN_CELL_AREA = 150  # Filter out noise/debris
SKIP_BG_RATE = 3     # Only grab background from every 3rd image (avoid bloat)

def harvest_assets():
    print(f"🚜 STARTING HARVEST from {INPUT_IMG_DIR}...")

    # Gather pairs
    pairs = []
    for f in os.listdir(INPUT_IMG_DIR):
        base = os.path.splitext(f)[0]
        # Robust mask matching
        candidates = [base + '_mask.png', base + '_mask.tif', base + '.png', base + '.tif']
        found_mask = None
        for c in candidates:
            if os.path.exists(os.path.join(INPUT_MASK_DIR, c)):
                found_mask = os.path.join(INPUT_MASK_DIR, c); break

        if found_mask:
            pairs.append((os.path.join(INPUT_IMG_DIR, f), found_mask))

    print(f"   -> Found {len(pairs)} valid image/mask pairs.")

    cell_count = 0
    bg_count = 0

    for i, (img_path, mask_path) in enumerate(tqdm(pairs, desc="Harvesting")):
        # Read
        try:
            img = cv2.imread(img_path); img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            if mask is None: mask = io.imread(mask_path)
        except: continue

        # Resize mask if needed
        if mask.shape[:2] != img.shape[:2]:
            mask = cv2.resize(mask, (img.shape[1], img.shape[0]), interpolation=cv2.INTER_NEAREST)

        mask_bin = (mask > 0).astype(np.uint8)

        # A. Extract Cells
        labels = measure.label(mask_bin)
        for region in measure.regionprops(labels):
            if region.area < MIN_CELL_AREA: continue

            # Expand bbox slightly for context
            minr, minc, maxr, maxc = region.bbox
            h, w = mask_bin.shape
            minr = max(0, minr-4); minc = max(0, minc-4)
            maxr = min(h, maxr+4); maxc = min(w, maxc+4)

            cell_chip = img[minr:maxr, minc:maxc]
            local_mask = (labels[minr:maxr, minc:maxc] == region.label).astype(np.uint8) * 255

            # Save
            cv2.imwrite(os.path.join(CELL_BANK, f"cell_{cell_count}.png"), cv2.cvtColor(cell_chip, cv2.COLOR_RGB2BGR))
            cv2.imwrite(os.path.join(CELL_BANK, f"cell_{cell_count}_mask.png"), local_mask)
            cell_count += 1

        # B. Extract Backgrounds (every Nth image)
        if i % SKIP_BG_RATE == 0:
            step = 512
            h, w = mask_bin.shape
            for y in range(0, h - step + 1, 256):
                for x in range(0, w - step + 1, 256):
                    patch_mask = mask_bin[y:y+step, x:x+step]
                    # Must be empty AND not black padding
                    if np.sum(patch_mask) == 0:
                        patch_img = img[y:y+step, x:x+step]
                        if patch_img.mean() > 40: # Not black
                            cv2.imwrite(os.path.join(BG_BANK, f"bg_{bg_count}.png"), cv2.cvtColor(patch_img, cv2.COLOR_RGB2BGR))
                            bg_count += 1

    print(f"✅ HARVEST COMPLETE.")
    print(f"   - Osteoclasts: {cell_count}")
    print(f"   - Backgrounds: {bg_count}")

    if cell_count < 50:
        raise ValueError("❌ CRITICAL: Too few cells extracted. Check your masks!")

harvest_assets()

from google.colab import drive
drive.mount('/content/drive')

import random

# --- GENERATOR CONFIG ---
NUM_SYNTHETIC = 500         # Target count
CELLS_PER_IMG = (4, 10)     # Density
OUTPUT_LOCAL_IMG = os.path.join(LOCAL_BASE, 'gen_images')
OUTPUT_LOCAL_MASK = os.path.join(LOCAL_BASE, 'gen_masks')

# Clean Output Dirs
for d in [OUTPUT_LOCAL_IMG, OUTPUT_LOCAL_MASK]:
    if os.path.exists(d): shutil.rmtree(d)
    os.makedirs(d, exist_ok=True)

def generate_synthetic_data_v2(num_images):
    print(f"🧪 GENERATING {num_images} SYNTHETIC IMAGES...")

    # Load file lists
    cell_files = [f for f in os.listdir(CELL_BANK) if f.endswith('.png') and '_mask' not in f]
    bg_files = [f for f in os.listdir(BG_BANK) if f.endswith('.png')]

    stats = {'success': 0, 'overlap_fail': 0, 'load_fail': 0}

    for i in tqdm(range(num_images), desc="Synthesizing"):
        # Retry loop for this specific image slot
        attempts = 0
        created = False

        while not created and attempts < 10:
            attempts += 1

            # 1. Base Canvas
            bg_name = random.choice(bg_files)
            bg = cv2.imread(os.path.join(BG_BANK, bg_name))
            bg = cv2.resize(bg, (512, 512))
            final_mask = np.zeros((512, 512), dtype=np.uint8)

            # 2. Add Cells
            num_cells = random.randint(CELLS_PER_IMG[0], CELLS_PER_IMG[1])
            placed_count = 0

            for _ in range(num_cells):
                # Pick random cell
                c_name = random.choice(cell_files)
                c_img = cv2.imread(os.path.join(CELL_BANK, c_name))
                c_mask = cv2.imread(os.path.join(CELL_BANK, c_name.replace('.png', '_mask.png')), cv2.IMREAD_GRAYSCALE)

                if c_img is None or c_mask is None: continue

                # Augmentations (Rotate/Flip/Scale)
                scale = random.uniform(0.7, 1.2)
                c_img = cv2.resize(c_img, (0,0), fx=scale, fy=scale)
                c_mask = cv2.resize(c_mask, (0,0), fx=scale, fy=scale, interpolation=cv2.INTER_NEAREST)

                if random.random() > 0.5:
                    c_img = cv2.flip(c_img, 1); c_mask = cv2.flip(c_mask, 1)

                # Check Size
                h, w = c_img.shape[:2]
                if h >= 512 or w >= 512: continue

                # Random Position
                y = random.randint(0, 512 - h)
                x = random.randint(0, 512 - w)

                # Strict Overlap Check
                existing_roi = final_mask[y:y+h, x:x+w]
                intersect = np.logical_and(existing_roi > 0, c_mask > 0).sum()
                if intersect > (0.2 * np.sum(c_mask > 0)): # Allow max 20% overlap
                    stats['overlap_fail'] += 1
                    continue

                # 3. Gaussian Blending (No jagged edges)
                roi_bg = bg[y:y+h, x:x+w]
                alpha = c_mask.astype(float) / 255.0
                alpha = cv2.GaussianBlur(alpha, (3,3), 0) # Smooth edge
                alpha_3 = np.stack([alpha]*3, axis=2)

                blended = (c_img * alpha_3) + (roi_bg * (1.0 - alpha_3))
                bg[y:y+h, x:x+w] = blended.astype(np.uint8)

                # Update Mask
                final_mask[y:y+h, x:x+w] = np.maximum(final_mask[y:y+h, x:x+w], c_mask)
                placed_count += 1

            if placed_count > 0:
                # Save
                fname = f"syn_v7_{i}"
                cv2.imwrite(os.path.join(OUTPUT_LOCAL_IMG, f"{fname}.png"), bg)
                cv2.imwrite(os.path.join(OUTPUT_LOCAL_MASK, f"{fname}_mask.png"), final_mask)
                stats['success'] += 1
                created = True

    print(f"\n✅ GENERATION FINISHED.")
    print(f"   - Created: {stats['success']} images")
    print(f"   - Overlaps Avoided: {stats['overlap_fail']}")

generate_synthetic_data_v2(NUM_SYNTHETIC)

def check_quality():
    files = os.listdir(OUTPUT_LOCAL_IMG)
    if not files: print("❌ No images generated!"); return

    print("🔬 QUALITY CONTROL CHECK (Random 3 Samples)")

    samples = random.sample(files, min(3, len(files)))
    plt.figure(figsize=(15, 5))

    for i, fname in enumerate(samples):
        img = cv2.imread(os.path.join(OUTPUT_LOCAL_IMG, fname))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        mask = cv2.imread(os.path.join(OUTPUT_LOCAL_MASK, fname.replace('.png', '_mask.png')), cv2.IMREAD_GRAYSCALE)

        # Overlay
        overlay = img.copy()
        overlay[mask > 0] = (255, 0, 0) # Red mask
        viz = cv2.addWeighted(img, 0.7, overlay, 0.3, 0)

        plt.subplot(1, 3, i+1)
        plt.imshow(viz)
        plt.title(f"Sample {i+1}")
        plt.axis('off')
    plt.show()

check_quality()

# --- FINAL SYNC ---
DRIVE_SYN_OUT = os.path.join(DRIVE_BASE, 'synthetic_experiment')
DRIVE_GEN_IMG = os.path.join(DRIVE_SYN_OUT, 'generated_images')
DRIVE_GEN_MASK = os.path.join(DRIVE_SYN_OUT, 'generated_masks')

print(f"💾 SYNCING RESULTS TO GOOGLE DRIVE ({DRIVE_SYN_OUT})...")

# Create Drive Folders
if not os.path.exists(DRIVE_SYN_OUT): os.makedirs(DRIVE_SYN_OUT)
if not os.path.exists(DRIVE_GEN_IMG): os.makedirs(DRIVE_GEN_IMG)
if not os.path.exists(DRIVE_GEN_MASK): os.makedirs(DRIVE_GEN_MASK)

# Copy Images
src_imgs = os.listdir(OUTPUT_LOCAL_IMG)
print(f"   -> Uploading {len(src_imgs)} images...")
for f in tqdm(src_imgs):
    shutil.copy2(os.path.join(OUTPUT_LOCAL_IMG, f), os.path.join(DRIVE_GEN_IMG, f))

# Copy Masks
src_masks = os.listdir(OUTPUT_LOCAL_MASK)
print(f"   -> Uploading {len(src_masks)} masks...")
for f in tqdm(src_masks):
    shutil.copy2(os.path.join(OUTPUT_LOCAL_MASK, f), os.path.join(DRIVE_GEN_MASK, f))

print("✅ SUCCESS. All synthetic data is safe on Google Drive.")

# CELL 1: SMART SUBSET LOADER (CPU OPTIMIZED)
# ---------------------------------------------------------
import os
import shutil
import random
from concurrent.futures import ThreadPoolExecutor
from tqdm.notebook import tqdm

# --- CONFIGURATION ---
SAMPLE_SIZE_CELLS = 3000     # We only need 3,000 cells for diversity (not all 30k)
SAMPLE_SIZE_BG = 500         # We only need 500 backgrounds

# Drive Paths (Source)
DRIVE_BASE = '/content/drive/MyDrive/CHANA_files/synthetic_experiment'
DRIVE_CELL_BANK = os.path.join(DRIVE_BASE, 'cell_bank')
DRIVE_BG_BANK = os.path.join(DRIVE_BASE, 'background_bank')

# Local Paths (Destination)
LOCAL_BASE = '/content/temp_gen_work'
LOCAL_CELL_BANK = os.path.join(LOCAL_BASE, 'cell_bank')
LOCAL_BG_BANK = os.path.join(LOCAL_BASE, 'background_bank')

# --- FAST COPY WORKER ---
def fast_copy(file_pair):
    src, dst = file_pair
    if not os.path.exists(dst):
        try:
            shutil.copy2(src, dst)
        except Exception as e:
            pass # Skip errors, we have plenty of other files

def load_subset_assets():
    print("🚀 STARTING SMART SUBSET LOAD...")

    # 1. Setup Local Dirs
    for d in [LOCAL_CELL_BANK, LOCAL_BG_BANK]:
        if os.path.exists(d): shutil.rmtree(d)
        os.makedirs(d, exist_ok=True)

    # 2. List & Sample Cells
    print("   Scanning Drive for Cells...", end="")
    all_cells = [f for f in os.listdir(DRIVE_CELL_BANK) if f.endswith('.png') and '_mask' not in f]
    print(f" Found {len(all_cells)} total.")

    # Pick random subset
    selected_cells = random.sample(all_cells, min(len(all_cells), SAMPLE_SIZE_CELLS))

    # Prepare Copy Tasks (Image + Mask)
    cell_tasks = []
    for f in selected_cells:
        # Image
        cell_tasks.append((os.path.join(DRIVE_CELL_BANK, f), os.path.join(LOCAL_CELL_BANK, f)))
        # Mask
        mask_name = f.replace('.png', '_mask.png')
        cell_tasks.append((os.path.join(DRIVE_CELL_BANK, mask_name), os.path.join(LOCAL_CELL_BANK, mask_name)))

    # 3. List & Sample Backgrounds
    print("   Scanning Drive for Backgrounds...", end="")
    all_bgs = [f for f in os.listdir(DRIVE_BG_BANK) if f.endswith('.png')]
    print(f" Found {len(all_bgs)} total.")

    selected_bgs = random.sample(all_bgs, min(len(all_bgs), SAMPLE_SIZE_BG))

    bg_tasks = []
    for f in selected_bgs:
        bg_tasks.append((os.path.join(DRIVE_BG_BANK, f), os.path.join(LOCAL_BG_BANK, f)))

    # 4. Execute Transfer
    total_files = len(cell_tasks) + len(bg_tasks)
    print(f"⚡ Transferring {total_files} files (Subset) to Local SSD...")

    all_tasks = cell_tasks + bg_tasks

    # Use 8 workers (safer for CPU runtime than 16)
    with ThreadPoolExecutor(max_workers=8) as executor:
        list(tqdm(executor.map(fast_copy, all_tasks), total=total_files, desc="Copying"))

    print("✅ SUBSET LOADED. Ready for Generation.")

# Run it
load_subset_assets()

# CELL: TURBO SYNC TO DRIVE (MULTITHREADED UPLOADER)
# ---------------------------------------------------------
import os
import shutil
from concurrent.futures import ThreadPoolExecutor
from tqdm.notebook import tqdm

# --- CONFIGURATION ---
# Local Source (Where your generated images are sitting right now)
LOCAL_BASE = '/content/temp_gen_work'
LOCAL_OUT_IMG = os.path.join(LOCAL_BASE, 'gen_images_new')
LOCAL_OUT_MASK = os.path.join(LOCAL_BASE, 'gen_masks_new')

# Drive Destination (Where they need to go)
DRIVE_BASE = '/content/drive/MyDrive/CHANA_files/synthetic_experiment'
DRIVE_GEN_IMG = os.path.join(DRIVE_BASE, 'generated_images')
DRIVE_GEN_MASK = os.path.join(DRIVE_BASE, 'generated_masks')

# --- WORKER FUNCTION ---
def fast_upload(file_info):
    src_path, dst_path = file_info
    # Only copy if it doesn't exist (or overwrite if you prefer)
    if not os.path.exists(dst_path):
        shutil.copy2(src_path, dst_path)

def upload_folder_multithreaded(local_folder, drive_folder, desc="Uploading"):
    if not os.path.exists(local_folder):
        print(f"⚠️ Warning: Local folder {local_folder} is empty or missing.")
        return

    # 1. Prepare List of Tasks
    files = [f for f in os.listdir(local_folder) if f.endswith(('.png', '.jpg'))]
    tasks = []

    for f in files:
        src = os.path.join(local_folder, f)
        dst = os.path.join(drive_folder, f)
        tasks.append((src, dst))

    if len(tasks) == 0:
        print(f"   No files found in {local_folder}.")
        return

    # 2. Execute with 16 Threads
    print(f"🚀 Turbo-Uploading {len(tasks)} files to {desc}...")

    with ThreadPoolExecutor(max_workers=16) as executor:
        list(tqdm(executor.map(fast_upload, tasks), total=len(tasks), desc=desc))

# --- EXECUTION ---
print("⚡ INITIALIZING HIGH-SPEED UPLOAD...")

# Ensure Drive folders exist
os.makedirs(DRIVE_GEN_IMG, exist_ok=True)
os.makedirs(DRIVE_GEN_MASK, exist_ok=True)

# Upload Images
upload_folder_multithreaded(LOCAL_OUT_IMG, DRIVE_GEN_IMG, desc="Images")

# Upload Masks
upload_folder_multithreaded(LOCAL_OUT_MASK, DRIVE_GEN_MASK, desc="Masks")

print("\n✅ SYNC COMPLETE. All files are safely on Drive.")